import {describe,expect,it} from "vitest";
import {draftReviewChanges,mechanicalRule,type ReviewGraphPreview} from "../draft-change-review-model";
import type {WorkspaceGraph,WorkspaceNode} from "@/lib/character/workspace/model";
const rule:WorkspaceNode={key:"primitive:1",kind:"primitive",id:"1",name:"Strength",bu:4,versionId:"v1",latestVersionId:"v1",userId:"owner",description:"Narrative flavor",data:{mechanicalOutputText:"Add +1 to Physical.",mechanicalDescription:"Legacy text"}};
function graph(nodes:WorkspaceNode[]=[rule]):WorkspaceGraph{return {characterId:"c",revision:0,nodes,edges:[{id:"slot",parent:null,child:"primitive:1",category:"LINEAGE",order:0,isMirrored:false}]};}
function preview(before:WorkspaceGraph,after:WorkspaceGraph):ReviewGraphPreview{return {graph:after,beforeSnapshot:{foundation:{name:"A",level:1},graph:before},afterSnapshot:{foundation:{name:"A",level:1},graph:after}};}
describe("character change review",()=>{
 it("shows the executable mechanical text before a narrative or legacy description",()=>{expect(mechanicalRule(rule)).toBe("Add +1 to Physical.");});
 it("uses beforeSnapshot and omits the unchanged library graph",()=>{const result=draftReviewChanges(preview(graph(),graph()));expect(result.hasBeforeGraph).toBe(true);expect(result.rules).toEqual([]);expect(result.placements).toEqual([]);expect(result.sources).toEqual([]);});
 it("shows before and after mechanical rules even when the title is unchanged",()=>{const next={...rule,data:{...rule.data,mechanicalOutputText:"Add +2 to Physical."}};const result=draftReviewChanges(preview(graph(),graph([next])));expect(result.rules).toEqual([{key:rule.key,title:"Strength",before:"Add +1 to Physical.\n4 BU",after:"Add +2 to Physical.\n4 BU"}]);});
 it("detects a placement-only move without claiming the primitive was edited",()=>{const after=graph();after.edges[0]!.category="MANIFEST";const result=draftReviewChanges(preview(graph(),after));expect(result.rules).toEqual([]);expect(result.placements[0]!.before).toContain("lineage");expect(result.placements[0]!.after).toContain("manifest");});
 it("shows loss of an equipped supply while preserving the same contained primitive",()=>{const item:WorkspaceNode={...rule,key:"item:bag",kind:"item",id:"bag",name:"Charm",data:{}};const before=graph([rule,item]);before.edges=[{id:"equipped",parent:null,child:item.key,category:"ITEM",order:0,isMirrored:false,data:{equipped:true}},{id:"contained",parent:item.key,child:rule.key,category:"ITEM",order:0,isMirrored:false}];const after=structuredClone(before);after.edges[0]!.data!['equipped']=false;const result=draftReviewChanges(preview(before,after));expect(result.rules).toEqual([]);expect(result.sources.find(change=>change.key===rule.key)).toMatchObject({before:"Available from 1 source",after:"Item is not equipped"});});
 it("compares foundation details and leaves unchanged fields out",()=>{const value=preview(graph(),graph());value.afterSnapshot!.foundation={name:"B",level:1,notes:"A trained bear"};const result=draftReviewChanges(value);expect(result.foundation.map(change=>change.title)).toEqual(["Name","Character concept / notes"]);expect(result.foundation[0]).toMatchObject({before:"A",after:"B"});});
 it("reviews the actual inverted rule when a supplied primitive becomes mirrored",()=>{const node={...rule,data:{...rule.data,hardModifiers:[{target:"max_vitality",operation:"add",value:5}]}};const before=graph([node]),after=graph([node]);after.edges[0]!.isMirrored=true;const result=draftReviewChanges(preview(before,after));expect(result.rules[0]!.after).toContain("subtract 5 from Max Vitality");expect(result.placements[0]!.after).toContain("mirrored");});
 it("does not treat a missing baseline as every rule being newly added",()=>{expect(draftReviewChanges({graph:graph()}).rules).toEqual([]);});
});
