"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {getEffectivePlayState,queuePlayChanges} from "@/lib/play-state/client-sync";
import {usePlaySession} from "@/lib/hooks/use-play-session";
import {PlaySessionPanel} from "@/components/characters/play-session-panel";
import {evaluateCondition} from "@/lib/engine/condition-evaluator";
import {rollDice} from "@/lib/engine/runtime-resolver";
import {resolveMonsterPlay,customMonsterConsequence} from "@/lib/monsters/play";
import type {PinnedDefinition} from "@/lib/monsters/service";
import type {ConsequenceOccurrence,ConsequenceBehavior} from "@/lib/character/consequences/types";
import type {HardModifier} from "@/types/swordweave";
import type {MonsterSlot} from "@/lib/monsters/resolve";
import {Markdown} from "@/components/ui/markdown";
import {MonsterSheetStats} from "./monster-sheet-stats";
import {Swords, Package, BookOpen, Activity, Heart, ChevronDown} from "lucide-react";
import "./monster-ui.css";
import "./monster-sheet.css";
export function MonsterPlaySheet({id}:{id:string}){
 const [tab,setTab]=useState<"capabilities"|"items"|"story"|"consequences"|"session">("capabilities");
 const [statsOpen,setStatsOpen]=useState(false);
 const [vitalityAmount,setVitalityAmount]=useState(1);
 const [packages,setPackages]=useState<{key:string;name:string;hash:string;vitalityDelta:number;pieces:{id:number;title:string;description:string;versionId:string|null;modifiers:HardModifier[];behavior:ConsequenceBehavior}[]}[]>([]);
 const [copyData,setCopyData]=useState<{accountId:string;copy:{name:string;templateVersion:number;currentVitality:number;definition:PinnedDefinition}}|null>(null),[error,setError]=useState(""),[roll,setRoll]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[consequenceTarget,setConsequenceTarget]=useState("attack_bonus"),[consequenceAmount,setConsequenceAmount]=useState(0),[deleteConfirmOpen,setDeleteConfirmOpen]=useState(false),[deleteConfirmAccount,setDeleteConfirmAccount]=useState<string|null>(null),[deletePending,setDeletePending]=useState(false);const deleteController=useRef<AbortController|null>(null);const endpoint=`/api/monsters/copies/${id}`;
 const syncEndpoint=`${endpoint}?session=1`;
 const {session,accountId}=usePlaySession("MONSTER_PLAY_COPY",id,syncEndpoint,undefined,{method:"PATCH"});
 useEffect(()=>{deleteController.current?.abort();deleteController.current=null;},[accountId,id]);
 useEffect(()=>{if(!accountId)return;let active=true;const abort=new AbortController();fetch(endpoint,{signal:abort.signal,cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);if(active){setCopyData({accountId,copy:b.copy});setPackages(b.packages??[]);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;abort.abort();};},[accountId,id,endpoint]);
 const copy=copyData?.accountId===accountId?copyData.copy:null;
 if(!copy||!session.ready)return <main className="p-6">{error||"Loading play copy…"}<PlaySessionPanel subjectKind="MONSTER_PLAY_COPY" subjectId={id} endpoint={syncEndpoint} method="PATCH"/></main>;
 const overrides=getEffectivePlayState("MONSTER_PLAY_COPY",id).overrides;const slots:MonsterSlot[]=copy.definition.resolvedSlots??[];const {sheet,occurrences,context}=resolveMonsterPlay(copy.definition,slots,overrides,copy.currentVitality);
 function change(field:string,value:unknown){queuePlayChanges("MONSTER_PLAY_COPY",id,[{field,value}]);}
 function check(label:string,bonus:number){const result=rollDice("1d20");setRoll(`${label}: ${result.rolls.join(" + ")} + ${bonus} = ${result.total+bonus}`);}
 async function deleteCopy(){if(deletePending||!accountId)return;setDeletePending(true);setError("");const controller=new AbortController();deleteController.current=controller;try{const response=await fetch(endpoint,{method:"DELETE",signal:controller.signal});if(controller.signal.aborted)return;const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error??"Unable to delete finished play copy.");location.href="/monsters";}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Unable to delete finished play copy.");}finally{if(deleteController.current===controller)deleteController.current=null;setDeletePending(false);}}
 const toggles=[...new Set(slots.flatMap(s=>(s.supplyKeys??[]).flat().filter(k=>k.startsWith("capability:")||k.startsWith("effect:"))))];
 return <main className="sw-monster-page monster-character-sheet" data-character-surface>
 <header className="creature-identity v12-instrument">
  <Link href="/monsters" className="creature-back">← Monsters &amp; NPCs</Link>
  <div className="creature-identity-row"><div className="creature-identity-glyph"><Swords aria-hidden="true"/></div><div><p className="creature-eyebrow">Private play copy · Version {copy.templateVersion}</p><h1>{copy.name}</h1><p className="creature-identity-meta">{copy.definition.size.toLowerCase()} · Rank {Number(sheet.rank.toFixed(2))} · {copy.definition.budget} BU</p></div><button className="creature-vitality-chip" onClick={()=>setStatsOpen(!statsOpen)} aria-expanded={statsOpen} aria-controls="creature-stats"><Heart size={15}/><strong>{sheet.currentVitality}</strong><span>/ {sheet.maximum}</span><ChevronDown size={14}/></button></div>
 </header>
 {error&&<p className="creature-error" role="alert">{error}</p>}
 <nav className="creature-tabs" aria-label="Play sheet sections">{([{key:"capabilities",label:"Capabilities",icon:Swords},{key:"items",label:"Items",icon:Package},{key:"story",label:"Story",icon:BookOpen},{key:"consequences",label:"Consequences",icon:Activity},{key:"session",label:"Session",icon:Heart}] as const).map(({key,label,icon:Icon})=><button key={key} type="button" aria-current={tab===key?"page":undefined} onClick={()=>setTab(key)}><Icon size={15}/>{label}{key==="consequences"&&occurrences.filter(c=>c.status!=="resolved").length>0&&<span>{occurrences.filter(c=>c.status!=="resolved").length}</span>}</button>)}</nav>
 <div className="creature-sheet-layout"><aside className="creature-stat-column" id="creature-stats" data-open={statsOpen}>
 <MonsterSheetStats sheet={sheet} proficientAttribute={copy.definition.proficientAttribute} onRoll={check}/>
 <section className="creature-vitality-controls"><h2>Track Vitality</h2><div className="creature-damage-row"><label>Amount<input type="number" min="1" value={vitalityAmount} onChange={e=>setVitalityAmount(Number(e.target.value))}/></label><button disabled={!Number.isSafeInteger(vitalityAmount)||vitalityAmount<1} onClick={()=>change("currentVitality",Math.max(0,sheet.currentVitality-vitalityAmount))}>Damage</button><button disabled={!Number.isSafeInteger(vitalityAmount)||vitalityAmount<1} onClick={()=>change("currentVitality",Math.min(sheet.maximum,sheet.currentVitality+vitalityAmount))}>Heal</button></div><label className="monster-field">Current Vitality<input type="number" min="0" max={sheet.maximum} value={sheet.currentVitality} onChange={e=>{const n=Number(e.target.value);if(Number.isSafeInteger(n)&&n>=0&&n<=sheet.maximum)change("currentVitality",n);}}/></label><details className="creature-baseline"><summary>Baseline Vitality override</summary><p>Changes the maximum. Current Vitality is only reduced when it exceeds the new maximum.</p><label className="monster-field">Manual baseline<input type="number" min="1" value={typeof overrides["baselineVitality"]==="number"?overrides["baselineVitality"]:copy.definition.baselineVitality??""} onChange={e=>{const n=Number(e.target.value);if(!e.target.value)change("baselineVitality",null);else if(Number.isSafeInteger(n)&&n>0)change("baselineVitality",n);}}/></label></details></section>
 </aside><div className="creature-content">
 {roll&&<output className="creature-roll-result" aria-live="polite">{roll}</output>}
 {tab==="story"&&<section className="creature-story"><p className="creature-eyebrow">Creature &amp; character</p><h2>{copy.name}</h2>{copy.definition.concept?<Markdown>{copy.definition.concept}</Markdown>:<p className="creature-empty">No story has been added to this template.</p>}{copy.definition.sourceOrigin&&<p className="creature-source">Origin: {copy.definition.sourceOrigin}</p>}<p className="creature-snapshot-note">This copy uses the saved template at version {copy.templateVersion}. Its play state is independent of the template and other copies.</p></section>}
 {tab==="items"&&<section className="creature-items"><h2>Items</h2>{slots.filter(s=>s.item).length===0&&<p className="creature-empty">This creature carries no items.</p>}{slots.filter(s=>s.item).map(s=><details className="creature-entity" key={s.dependencyKey}><summary><Package size={17}/><strong>{s.name}</strong><span>×{s.quantity}</span></summary><div className="creature-entity-body"><p>{s.buCost} BU each{s.isMirrored?" · Mirrored":""}</p>{s.hardModifiers.map((m,i)=><p key={i}>{m.target.replaceAll("_"," ")}: {m.operation} {typeof m.value==="object"?JSON.stringify(m.value):String(m.value)}</p>)}</div></details>)}</section>}

 <section className="monster-panel monster-abilities-panel" hidden={tab!=="capabilities"}><h2 className="text-xl">Capabilities &amp; effects</h2><p className="creature-section-intro">Use an ability to apply its consequences. Disable a capability or effect to remove its contribution from this copy.</p><div className="creature-capability-list">{packages.length===0&&<p className="creature-empty">No usable abilities in this copy. Its passive rules are listed below.</p>}{packages.map(p=><article className="creature-capability" key={p.key}><div className="creature-capability-heading"><Swords size={17}/><h3>{p.name}</h3><span>{p.key.startsWith("effect:")?"Effect":"Capability"}</span></div>{p.pieces.map(piece=><div className="creature-capability-effect" key={piece.id}><strong>{piece.title}</strong>{piece.description&&<Markdown>{piece.description}</Markdown>}</div>)}{p.vitalityDelta!==0&&<p className="creature-capability-delta">Vitality {p.vitalityDelta>0?"+":""}{p.vitalityDelta} on use</p>}<button className="creature-use-button" key={p.key} disabled={p.key.startsWith("capability:")&&overrides[p.key.replace("capability:","cap:")]===true||p.key.startsWith("effect:")&&overrides[p.key.replace("effect:","eff:")]===true} onClick={()=>{const applicationId=crypto.randomUUID();const changes=p.pieces.map(piece=>{const occurrence:ConsequenceOccurrence={...customMonsterConsequence(piece.title,piece.description),id:crypto.randomUUID(),applicationId,sourceEntityId:String(piece.id),sourceEntityType:"primitive",sourceVersionId:piece.versionId,modifiers:piece.modifiers,restrictions:piece.behavior.restrictions,recovery:piece.behavior.recovery,applicationSnapshot:{vitalityDelta:piece.behavior.vitalityDelta,modifiers:piece.modifiers,restrictions:piece.behavior.restrictions}};return {field:`consequence:${occurrence.id}`,value:occurrence as unknown};});changes.push({field:"currentVitality",value:Math.max(0,Math.min(sheet.maximum,sheet.currentVitality+p.vitalityDelta))});queuePlayChanges("MONSTER_PLAY_COPY",id,changes);}}>Use {p.name}</button></article>)}</div><h3 className="creature-rules-heading">Active rules</h3>{toggles.map(k=>{const field=k.replace("capability:","cap:").replace("effect:","eff:");const displayName=slots.find(s=>s.supplyNames?.[k])?.supplyNames?.[k]??k;return <label className="monster-check" key={k}><input type="checkbox" checked={overrides[field]!==true} onChange={e=>change(field,e.target.checked?null:true)}/>Enable {displayName}</label>;})}{slots.filter(s=>!s.item).map(s=><details className="monster-slot-detail creature-entity" key={s.dependencyKey}><summary><Swords size={17}/><strong>{s.name}</strong><span>×{s.quantity}{s.isMirrored?" · mirrored":""}</span></summary>{s.hardModifiers.map((m,i)=><p key={i}>{m.target.replaceAll("_"," ")}: {m.operation} {typeof m.value==="object"?JSON.stringify(m.value):String(m.value)}</p>)}</details>)}</section>
 <section className="monster-panel monster-consequences-panel" hidden={tab!=="consequences"}>
  <h2>Consequences</h2>
  {occurrences.length===0&&<p className="creature-empty">No consequences yet. Applied abilities and custom consequences appear here.</p>}
  {occurrences.map(c=><article className="monster-consequence" key={c.id}>
   <div><strong>{c.title}</strong><span className="creature-status">{c.status==="resolved"?"Resolved":c.source==="sheet-auto"?"Automatic":"Ongoing"}</span>{c.description&&<p>{c.description}</p>}</div>
   <div className="monster-actions"><label className="monster-check"><input type="checkbox" checked={c.status!=="resolved"&&(c.manualOverride??(c.source==="sheet-auto"?evaluateCondition(c.modifiers[0]?.condition as never,context):c.active))} onChange={e=>change(`consequence:${c.id}`,{...c,manualOverride:e.target.checked})}/>Active</label>
    <button onClick={()=>change(`consequence:${c.id}`,{...c,status:"resolved",active:false,manualOverride:false,resolvedAt:Date.now()})}>Resolve</button>
    {c.source==="custom"&&<button onClick={()=>change(`consequence:${c.id}`,null)}>Delete</button>}
   </div>
  </article>)}
  <h3>Add a consequence</h3>
  <div className="monster-settings-grid">
   <label className="monster-field">Title<input aria-label="Consequence title" placeholder="Consequence" value={title} onChange={e=>setTitle(e.target.value)}/></label>
   <label className="monster-field">Description<textarea aria-label="Consequence description" value={description} onChange={e=>setDescription(e.target.value)}/></label>
  </div>
  <label className="monster-field">Optional modifier<div className="monster-modifier-row"><select aria-label="Modifier target" value={consequenceTarget} onChange={e=>setConsequenceTarget(e.target.value)}>{["attack_bonus","save_dc","max_vitality","speed","physical_saving_throw","mental_saving_throw","magical_saving_throw","attribute.physical","attribute.mental","attribute.magical",...sheet.practices.map(p=>`skill_practice_check.${p.practice}`)].map(k=><option key={k}>{k}</option>)}</select><input aria-label="Modifier amount" type="number" value={consequenceAmount} onChange={e=>setConsequenceAmount(Number(e.target.value))}/></div></label>
  <button disabled={!title.trim()} onClick={()=>{const c=customMonsterConsequence(title.trim(),description);if(Number.isSafeInteger(consequenceAmount)&&consequenceAmount!==0)c.modifiers=[{kind:"modify",target:consequenceTarget,operation:"add",value:consequenceAmount,stacking:"stack"}];change(`consequence:${c.id}`,c);setTitle("");setDescription("");}}>Add consequence</button>
 </section>
 <section className="creature-session" hidden={tab!=="session"}><h2>Saved session</h2><p className="creature-section-intro">Manage synchronization, conflicts, offline changes, and backups for this private copy.</p><PlaySessionPanel subjectKind="MONSTER_PLAY_COPY" subjectId={id} endpoint={syncEndpoint} method="PATCH"/>
 {deleteConfirmOpen&&deleteConfirmAccount===accountId?<section className="monster-panel monster-delete-confirm" aria-labelledby="monster-delete-heading"><h2 id="monster-delete-heading">Delete {copy.name}?</h2><p>This permanently deletes this private play copy and its saved session.</p><div className="monster-actions"><button type="button" disabled={deletePending} onClick={()=>setDeleteConfirmOpen(false)}>Keep this copy</button><button className="monster-delete-copy" type="button" disabled={deletePending} onClick={()=>void deleteCopy()}>{deletePending?"Deleting…":"Delete finished copy"}</button></div>{deletePending&&<p role="status">Deleting private play copy…</p>}</section>:<button className="monster-delete-copy" type="button" onClick={()=>{setDeleteConfirmAccount(accountId);setDeleteConfirmOpen(true);}}>Delete finished copy</button>}</section></div></div></main>;
}
