"use client";
import {Swords,Footprints} from "lucide-react";
import {VitalityDisplayCard} from "@/components/characters/vitality-display-card";
import type {resolveMonster} from "@/lib/monsters/resolve";
import type {MonsterDefinition} from "@/lib/monsters/model";
const signed=(value:number)=>`${value>=0?"+":""}${value}`;
export function MonsterSheetStats({sheet,proficientAttribute,definition,baselineVitality,onRoll}:{sheet:ReturnType<typeof resolveMonster>;proficientAttribute:string;definition?:MonsterDefinition;baselineVitality?:number;onRoll?:(label:string,bonus:number)=>void}) {
 const totals=sheet.resolved.totals;
 const attribute=proficientAttribute as "physical"|"mental"|"magical";
 return <div className="v12-drawer-section space-y-3"><VitalityDisplayCard current={sheet.currentVitality} max={sheet.maximum} pb={totals["proficiency_bonus"]??sheet.pb} proficientAttribute={attribute} resolver={sheet.resolved} resolverInput={{characterId:"monster",level:sheet.rank,pb:sheet.pb,attributes:definition?.attributes??sheet.attributes,proficientAttribute:attribute,slots:[]}} displayTotals={{totals,baselinePb:sheet.pb,baselineVitality:baselineVitality??definition?.baselineVitality??sheet.vitality,proficiencyFormula:"PB = 1 + ceil(rank), then apply modifiers. Rank = √(BU / 25).",vitalityFormula:"Baseline Vitality = ceil(BU / 2), or the manual override, then apply modifiers."}}/><div className="v12-drawer-section v12-drawer-derived grid grid-cols-2 gap-2"><button className="v12-metal-button flex justify-between items-center" disabled={!onRoll} onClick={()=>onRoll?.("Attack",totals["attack_bonus"]??0)}><Swords size={14}/><span>Attack</span><strong>{signed(totals["attack_bonus"]??0)}</strong></button><div className="rounded border border-border bg-card p-2 flex items-center justify-between text-xs"><Footprints size={14}/><span>Speed</span><strong>{totals["speed"]??0}</strong></div></div><section className="v12-drawer-section v12-drawer-practices"><h3 className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Practices</h3><div className="grid grid-cols-2 gap-1">{sheet.practices.map(p=><button className="v12-metal-button flex justify-between gap-2 text-xs" key={p.practice} disabled={!onRoll} onClick={()=>onRoll?.(p.practice,p.total)}><span className="capitalize">{p.practice.replaceAll("_"," ")}</span><strong>{signed(p.total)}</strong></button>)}</div><div className="mt-3 flex flex-wrap gap-1">{(["physical","mental","magical"] as const).map(key=><button className="v12-metal-button text-xs" key={key} disabled={!onRoll} onClick={()=>onRoll?.(`${key} save`,totals[`${key}_saving_throw`]??0)}>Roll {key} save</button>)}</div></section></div>;
}
