"use client";
import { useState } from "react";
import { Dice5 } from "lucide-react";
import { VitalityDisplayCard } from "@/components/characters/vitality-display-card";
import { FormulaModal, contributionsToSteps, type FormulaStep } from "@/components/characters/formula-modal";
import { PRACTICE_DESCRIPTIONS, type Practice } from "@/lib/primitives/target-scope";
import { SIZE_BASE_SPEED, SIZE_CAPACITY, SIZE_LOAD } from "@/lib/engine/encumbrance";
import type { resolveMonster } from "@/lib/monsters/resolve";
import type { MonsterDefinition } from "@/lib/monsters/model";
type Sheet = ReturnType<typeof resolveMonster>;
type Props = {sheet:Sheet; proficientAttribute:string; definition?:MonsterDefinition; baselineVitality?:number; showPractices?:boolean; onRoll?:(label:string,bonus:number)=>void};
const signed=(value:number)=>`${value>=0?"+":""}${value}`;
const label=(value:string)=>value.replaceAll("_"," ").replace(/^./,letter=>letter.toUpperCase());
/** Keep source operations visible, while numeric ledger entries reconcile to the resolver. */
export function monsterFormulaSteps(target:string,sheet:Sheet,base:FormulaStep[],total:number,adjustmentLabel="Resolved multipliers, bounds, and rounding"):FormulaStep[] {
 const seen=new Set();
 const sources=contributionsToSteps(target,sheet.resolved).filter(step=>{if(seen.has(step.contribution))return false;seen.add(step.contribution);return true;}).map(step=>{
  const c=step.contribution;
  return {...step,value:!c||c.inhibited||c.conditionActive===false?null:c.op==="add"?c.value:c.op==="subtract"?-c.value:null};
 });
 const steps=[...base,...sources];
 const difference=total-steps.reduce((sum,step)=>sum+(step.value??0),0);
 return difference?[...steps,{label:adjustmentLabel,value:difference}]:steps;
}
export function monsterPracticeSteps(sheet:Sheet,practice:Sheet["practices"][number],definition?:MonsterDefinition):FormulaStep[] {
 const attribute=practice.attribute.toLowerCase() as keyof Sheet["attributes"];
 const attributeSteps=definition?monsterFormulaSteps(`attribute.${attribute}`,sheet,[{label:`Starting ${label(attribute)}`,value:definition.attributes[attribute]}],practice.slice,`${label(attribute)} multipliers, bounds, and rounding`):[{label:`${label(attribute)} attribute`,value:practice.slice}];
 const pbSteps=practice.pbContribution!==0||definition?.proficientAttribute===attribute?monsterFormulaSteps("proficiency_bonus",sheet,[{label:"Rank proficiency bonus",value:sheet.pb}],practice.pbContribution,"Specialty PB adjustments"):[];
 return monsterFormulaSteps(`skill_practice_check.${practice.practice}`,sheet,[...attributeSteps,...pbSteps],practice.total,"Practice multipliers, bounds, and rounding");
}
const SIZES=["TINY","SMALL","MEDIUM","LARGE","HUGE","GARGANTUAN"] as const;
function PracticeInfo({practice}:{practice:Sheet["practices"][number]}) {
 const info=PRACTICE_DESCRIPTIONS[practice.practice.toUpperCase() as Practice];
 return <div className="space-y-2"><p><strong>{info.coreQuestion}</strong></p><p>{info.description}</p><p>Roll d20 {signed(practice.total)} when the outcome is uncertain. The governing attribute contributes its full value; specialty adds PB.</p><details className="v12-practice-boundary"><summary>May include</summary><ul className="list-disc pl-4">{info.mayInclude.map(item=><li key={item}>{item}</li>)}</ul></details><details className="v12-practice-boundary"><summary>Examples</summary><ul className="list-disc pl-4">{info.examples.map(item=><li key={item}>{item}</li>)}</ul></details>{info.versus&&<details className="v12-practice-boundary"><summary>Practice boundary</summary><p>{info.versus}</p></details>}</div>;
}
export function MonsterPracticeGrid({sheet,definition,onRoll}:{sheet:Sheet;definition?:MonsterDefinition;onRoll?:Props["onRoll"]}) {
 const [selected,setSelected]=useState<Sheet["practices"][number]|null>(null);
 const steps=selected?monsterPracticeSteps(sheet,selected,definition):[];
 return <section className="v12-drawer-section v12-drawer-practices"><div className="monster-practice-columns">{(["physical","mental","magical"] as const).map(attr=><section className="monster-practice-column" key={attr}><h3>{label(attr)} <strong>{signed(sheet.attributes[attr])}</strong></h3>{sheet.practices.filter(p=>p.attribute.toLowerCase()===attr).map(practice=><div className="monster-practice-row" key={practice.practice}><button type="button" className="monster-stat-open" aria-label={`Explain ${practice.practice} ${signed(practice.total)}`} onClick={()=>setSelected(practice)}><span>{label(practice.practice)}</span><strong>{signed(practice.total)}</strong></button>{onRoll&&<button type="button" className="monster-stat-roll" aria-label={`Roll ${practice.practice}`} onClick={()=>onRoll(label(practice.practice),practice.total)}><Dice5 size={14}/></button>}</div>)}</section>)}</div>{selected&&<FormulaModal title={label(selected.practice)} total={selected.total} subtitle={`${label(selected.attribute.toLowerCase())} practice`} formula="Practice = governing attribute + PB from specialty + primitive and consequence modifiers. Click Roll to make a d20 check." breakdown={steps} info={{title:"Using this practice",body:<PracticeInfo practice={selected}/>}} onClose={()=>setSelected(null)}/>}</section>;
}
export function MonsterSheetStats({sheet,proficientAttribute,definition,baselineVitality,onRoll,showPractices=true}:Props) {
 const [metric,setMetric]=useState<string|null>(null);
 const totals=sheet.resolved.totals;
 const attribute=proficientAttribute as "physical"|"mental"|"magical";
 const size=definition?.size??"MEDIUM";
 const resolvedPb=totals["proficiency_bonus"]??sheet.pb;
 const attackAttribute=sheet.resolved.chosenAttribute??attribute;
 const attackBases=[...monsterFormulaSteps("proficiency_bonus",sheet,[{label:"Rank proficiency bonus",value:sheet.pb}],resolvedPb,"Proficiency multipliers, bounds, and rounding"),...(definition?monsterFormulaSteps(`attribute.${attackAttribute}`,sheet,[{label:`Starting ${label(attackAttribute)}`,value:definition.attributes[attackAttribute]}],sheet.attributes[attackAttribute],"Attribute multipliers, bounds, and rounding"):[{label:`${label(attackAttribute)} specialty`,value:sheet.attributes[attackAttribute]}])];
 const metricInfo=metric==="speed"?{title:"Movement speed",total:totals["speed"]??0,formula:"Speed = the creature's size speed, then apply movement primitives and consequences.",steps:monsterFormulaSteps("speed",sheet,[{label:`${label(size.toLowerCase())} base speed`,value:SIZE_BASE_SPEED[size]}],totals["speed"]??0),info:{title:"Speed by size",body:<div><table className="w-full text-xs"><thead><tr><th className="text-left">Size</th><th>Walk</th><th>Swim</th><th>Climb</th></tr></thead><tbody>{SIZES.map(value=><tr key={value} aria-current={value===size?"true":undefined}><td>{label(value.toLowerCase())}</td><td>{SIZE_BASE_SPEED[value]} ft</td><td>{Math.ceil(SIZE_BASE_SPEED[value]/2)} ft</td><td>{Math.ceil(SIZE_BASE_SPEED[value]/2)} ft</td></tr>)}</tbody></table><p>Swim and climb default to half the base walking speed, rounded up. Burrow and flight start at 0 and must be granted by primitives.</p></div>}}:metric==="carry_capacity"?{title:"Load capacity",total:totals["carry_capacity"]??0,formula:"Load capacity = size capacity + starting Physical × 5, then apply primitives and consequences.",steps:monsterFormulaSteps("carry_capacity",sheet,[{label:"Size capacity",value:SIZE_CAPACITY[size]},{label:"Starting Physical × 5",value:(definition?.attributes.physical??sheet.attributes.physical)*5}],totals["carry_capacity"]??0),info:{title:"Carrying and size",body:<div><p>Capacity is how much the creature can carry. Load is the combined size load of carried items, including equipped items. A creature is encumbered when Load exceeds Capacity.</p><div className="v12-size-reference">{SIZES.map(value=><article className={value===size?"is-current":""} key={value}><strong>{label(value.toLowerCase())}</strong><span><small>Capacity</small>{SIZE_CAPACITY[value]}</span><span><small>Load / item</small>{value==="TINY"?"0*":SIZE_LOAD[value]}</span></article>)}<p>Tiny items use pouches: 1 pouch holds up to 1000 tiny items and costs 1 Load. This includes coins, gems, scrolls, and nails.</p></div><p>The creature uses its starting Physical value for the carrying baseline. Carrying primitives and consequences modify this capacity.</p></div>}}:{title:"Attack bonus",total:totals["attack_bonus"]??0,formula:"Attack = PB + specialty attribute + attack primitives and consequences. Roll d20 + this bonus against the target's DC.",steps:monsterFormulaSteps("attack_bonus",sheet,attackBases,totals["attack_bonus"]??0,"Resolver attack scaling, multipliers, bounds, and rounding"),info:{title:"Attribute-driven attack",body:<div><p>Roll d20 {signed(totals["attack_bonus"]??0)} against the target’s DC. Attack scales with the creature’s {label(attackAttribute).toLowerCase()} specialty attribute, its proficiency bonus, and attack-specific primitives.</p><p>Attribute values contribute directly. The active resolver applies primitive operations and consequences to determine the final bonus.</p></div>}};

 return <div className="space-y-3 monster-sheet-stats"><VitalityDisplayCard layout="drawer" drawerAttack={{value:totals["attack_bonus"]??0,onOpen:()=>setMetric("attack_bonus")}} current={sheet.currentVitality} max={sheet.maximum} pb={totals["proficiency_bonus"]??sheet.pb} proficientAttribute={attribute} resolver={sheet.resolved} resolverInput={{characterId:"monster",level:sheet.rank,pb:sheet.pb,attributes:definition?.attributes??sheet.attributes,proficientAttribute:attribute,slots:[]}} displayTotals={{totals,baselinePb:sheet.pb,baselineVitality:baselineVitality??definition?.baselineVitality??sheet.vitality,proficiencyFormula:"PB = 1 + ceil(rank), then apply modifiers. Rank = √(BU / 25).",vitalityFormula:"Baseline Vitality = ceil(BU / 2), or the manual override, then apply modifiers."}}/><div className="v12-drawer-section v12-drawer-derived monster-metric-grid">{[{key:"speed",name:"Speed",value:`${totals["speed"]??0} ft`},{key:"carry_capacity",name:"Load",value:String(totals["carry_capacity"]??0)}].map(item=><button key={item.key} className="monster-stat-open" aria-label={`Explain ${item.name}`} onClick={()=>setMetric(item.key)}><span>{item.name}</span><strong>{item.value}</strong></button>)}</div>{showPractices&&<MonsterPracticeGrid sheet={sheet} {...(definition?{definition}:{})} {...(onRoll?{onRoll}:{})}/> }{onRoll&&<div className="monster-roll-actions"><button className="creature-sheet-button" onClick={()=>onRoll("Attack",totals["attack_bonus"]??0)}><Dice5 size={14}/>Roll attack</button>{(["physical","mental","magical"] as const).map(key=><button className="creature-sheet-button" key={key} onClick={()=>onRoll(`${label(key)} save`,totals[`${key}_saving_throw`]??0)}>Roll {key} save</button>)}</div>}{metric&&<FormulaModal title={metricInfo.title} total={metricInfo.total} formula={metricInfo.formula} breakdown={metricInfo.steps} info={metricInfo.info} onClose={()=>setMetric(null)}/>}</div>;
}
