import Link from "next/link";
import { ArrowRight, BookOpen, Boxes, Compass, Hammer, Layers3, Sparkles, Swords } from "lucide-react";
import type { Metadata } from "next";
import { PublicNav } from "@/components/home/public-nav";

export const metadata: Metadata = {
  title: "How to play · SwordWeave",
  description: "Follow Bartholomew from character concept through starting access, sheet composition, and a turn at the table.",
};

const STEPS = [
  { id:"character", number:"01", icon:Compass, phase:"Create / Your character", title:"Meet the person before the rules.", body:"Open Create character. Give them a name and a concept: who they are, what they can do, and why you want to play them. Add their appearance, personality, history, goals, ties, and conflict as far as you know them. A description can exist before you attach any primitives. It tells you what you want to build; it does not silently purchase the mechanics.", example:"Bartholomew Vey is a refined psychic serpent, a gentleman with copper-and-amber scales and an immaculate top hat. He wants to understand consciousness. Other people’s memories have begun to blur with his own.", label:"An actual character’s concept" },
  { id:"foundation", number:"02", icon:Compass, phase:"Create / Foundation", title:"Give that idea a starting point.", body:"Choose a level or starting budget and physical size. Distribute 10 points across Physical, Mental, and Magical, with each score from −1 to 5. Choose an attribute specialty for proficiency in its related practices and saves. Presets give you a quick foundation; you can adjust individual scores. This is not the step where you finish every proficiency or ability.", example:"For a patient investigator of minds, consider a Mental or Magical emphasis. Decide what fits your version of the character; Bartholomew’s story does not prescribe a single attribute spread.", label:"A choice for your table" },
  { id:"weakness", number:"03", icon:Sparkles, phase:"Create / Weakness", title:"Decide whether a drawback belongs here.", body:"The Weakness step is optional. Pick a mirrored rule only if its actual drawback fits the character. Read its result and credit, and stay within the level’s combined drawback limit. A story flaw can remain a description without becoming a mechanical weakness. Skipping this step is fine.", example:"His uncertainty about which memories are his own is a story conflict. If you want a mechanical cost too, choose a rule whose mirrored result expresses it. The backstory alone grants no extra BU.", label:"Story and mechanics, chosen deliberately" },
  { id:"rules", number:"04", icon:Boxes, phase:"Create / Starting access → Ready to play", title:"Choose a base package. Leave room to grow.", body:"Choose a suggested starting set or make your own from four access families: Domain, Verb Tier, Range, and Output Die. Read the definitions and fit the package within your available BU. Review the foundation, weakness, and access, then create the character. You do not need to spend every point. Heritages, capabilities, items, and further proficiencies are built on the character sheet afterward.", example:"Bartholomew’s existing sheet includes Belief and Emotion domain access, Verb Access Tiers I and II, Near Range (30 ft), and an Impact Die Block (1d10). These are examples of owned access from his current build, not a prescribed or complete starting package.", label:"Actual access on his sheet" },
  { id:"compose", number:"05", icon:Layers3, phase:"On the sheet / Edit mode", title:"Turn the foundation into a character package.", body:"Now compose Lineage, Upbringing, and Manifest on the sheet. Give each a name and description even if its mechanics are still unfinished. Add primitives and capabilities where they belong. A capability can contain primitives and optional effects; an effect is a reusable group of mechanical pieces. Add items and further rules as the idea develops. Preview the pieces, review the draft, then apply it to return to play.", example:"The Dreamcoil is his Lineage; The Gentleman Among Humans is his Upbringing; The Cartographer of Minds is his Manifest. Those names tell a story. Open each heritage to see which rules and capabilities it actually contains.", label:"Bartholomew’s three heritages" },
  { id:"table", number:"06", icon:Swords, phase:"At the table / Declare an intent", title:"A scene begins. What do you do?", body:"You can use a saved capability or improvise an action from primitives your character already owns. Say the intent in ordinary language. Show which owned rules support it. A dramatic name or domain flavor cannot supply missing access. In combat, declare with the group during Council; the GM considers the intent’s complexity and the situation to place it in the round.", example:"At a crowded reception, a courier reaches for a concealed weapon. Bartholomew says, “I want to stir his doubt for a moment, long enough for my companion to move away.” This is an illustrative attempt inspired by the character, not a guaranteed power in his saved build.", label:"A proposed scene" },
  { id:"scale", number:"07", icon:Sparkles, phase:"At the table / Agree scope and cost", title:"Make the important details explicit.", body:"How many people? How far away? How long? What is being changed, and how strongly? Discuss scale, impact, complexity, conditions, and the surrounding danger. The GM checks feasibility and agrees cost and consequences before commitment. Cost might be Vitality, a resource, a hazard, a narrative twist, lost access, or a condition. Accept it, reduce the scope, propose another approach, or stop before rolling. Optional capability scaling declarations help remember a familiar use; they are not the whole capability. Duration and upkeep are separate: an effect may last without active maintenance; if it is actively maintained, agree upkeep at the start of each turn. The sheet’s guidance supports the conversation, while the table makes the ruling.", example:"One nearby courier for a moment is different from every guest for the whole evening. Check the available domain, action tier, range, and other relevant rules. If the broader attempt is possible, agree its additional strain or other consequences rather than assuming it is free.", label:"The same idea, different stakes" },
  { id:"resolve", number:"08", icon:BookOpen, phase:"At the table / Resolve and continue", title:"Choose the right resolution together.", body:"Agree who rolls, what they roll, what opposes them, and what success or failure means. The available declarations cover your action roll, a target’s saving throw, a target’s practice check against a DC, opposed checks, and no roll. Leave a saved resolution unspecified when the scene must decide it. A resolution note grants no bonus, proficiency, access, or extra action.", example:"The GM might call for the courier’s Mental save against the relevant DC, an opposed check if both sides actively struggle, or no roll if nothing uncertain is being contested. Decide from the actual rules and scene. Apply the outcome and any consequences, then respond to the changed situation.", label:"A ruling, not a predetermined result" },
] as const;

export default function StartPage(){return <div className="sw-home sw-public-site sw-public-site--arcane sw-guide-walkthrough">
  <PublicNav/><div id="main-content">
    <header className="sw-public-hero sw-guide-hero"><div><p className="sw-public-kicker"><Compass aria-hidden="true"/> Your first adventure / field guide</p><h1 className="sw-public-title">First, a character.<br/><em>Then, a possibility.</em></h1><p className="sw-public-deck">Start with someone you want to play. Give them a foundation in character creation. Build their full package on the sheet. Bring their rules and your imagination to the table.</p><div className="sw-public-actions"><Link className="sw-cta-primary" href="/characters/new">Create a character <ArrowRight aria-hidden="true"/></Link><a className="sw-cta-ghost" href="#character">Follow the walkthrough <BookOpen aria-hidden="true"/></a></div></div>
    <aside className="sw-guide-example" aria-label="Meet Bartholomew Vey"><div className="sw-guide-example__heading"><span className="sw-guide-sigil"><Compass aria-hidden="true"/></span><div><p className="sw-public-kicker">Meet an existing character</p><h2>Bartholomew Vey</h2><p>A psychic serpent. An impeccable gentleman. A mind full of borrowed memories.</p></div></div><ol className="sw-guide-flow"><li><span className="sw-guide-flow__marker"><Sparkles aria-hidden="true"/></span><div><span className="sw-guide-flow__label">The person</span><p>He studies consciousness, but fears losing the boundary of his own identity.</p></div></li><li><span className="sw-guide-flow__marker"><Boxes aria-hidden="true"/></span><div><span className="sw-guide-flow__label">The foundation</span><p>Domains, verb tiers, range, and an output die provide actual mechanical access.</p></div></li><li><span className="sw-guide-flow__marker"><Swords aria-hidden="true"/></span><div><span className="sw-guide-flow__label">The possibility</span><p>“Could I turn the courier’s certainty into a moment of doubt?”</p></div></li></ol><p className="sw-guide-example__foot">His concept, heritage names, and listed access come from an existing character. The scene and proposed rulings below are teaching examples.</p></aside></header>
    <nav className="sw-public-jump" aria-label="Walkthrough chapters"><a href="#character">I / Create the foundation</a><a href="#compose">II / Compose on the sheet</a><a href="#table">III / Play a scene</a></nav>
    <section className="sw-public-section" aria-label="From concept through creation to play"><ol className="sw-public-walkthrough">{STEPS.map(step=><li id={step.id} key={step.id} className="sw-public-panel sw-public-step"><div><span className="sw-public-number">{step.number}</span><step.icon aria-hidden="true"/></div><div><p className="sw-public-kicker">{step.phase}</p><h2>{step.title}</h2><p>{step.body}</p></div><aside className="sw-public-example"><span className="sw-public-kicker">{step.label}</span><p>{step.example}</p></aside></li>)}</ol></section>
    <section className="sw-public-section" aria-labelledby="turn-title"><header className="sw-public-section-head"><div><p className="sw-public-kicker">One possible turn / an illustrative ruling</p><h2 id="turn-title">The courier hesitates.<br/><em>The scene moves forward.</em></h2></div><p>Suppose the GM confirms that this modest attempt fits the owned rules, assigns it to Measured, and calls for the courier’s Mental save. The table agrees the DC, cost, and brief outcome before committing.</p></header>
      <ol className="sw-guide-turn">
        <li><span>01 / Council</span><h3>Declare together.</h3><p>Bartholomew states his intent. His companion plans to move clear. The GM makes the courier’s visible threat understood.</p></li>
        <li><span>02 / Fast → Measured → Heavy</span><h3>Let the scene develop.</h3><p>Resolve Fast intents first. When Measured arrives, check that the attempt still makes sense. In this example it does; resolve the agreed save.</p></li>
        <li><span>03 / The result</span><h3>A moment of doubt.</h3><p>Suppose the courier fails the save. Apply the agreed hesitation and cost. His companion moves clear when their intent resolves; the courier has not become a puppet or forgotten the encounter.</p></li>
        <li><span>04 / Carry forward</span><h3>A different next round.</h3><p>Finish the remaining intents, record consequences, and check any ongoing effects or upkeep. At the next Council, the courier faces a changed scene and the group declares again.</p></li>
      </ol><p className="sw-guide-turn__note">If the save had succeeded or an earlier action had changed the situation, follow that result instead. Fast, Measured, and Heavy are complexity tracks, not a guarantee that every declared plan completes unchanged.</p>
    </section>
    <section className="sw-public-section" aria-labelledby="sheet-title"><header className="sw-public-section-head"><div><p className="sw-public-kicker">Keep the reference close</p><h2 id="sheet-title">The sheet supports<br/><em>the conversation.</em></h2></div><p>Open the lower sheet drawer when you need character numbers and guidance. Read the mechanical rules behind a piece before using its name as shorthand.</p></header><div className="sw-public-grid"><article className="sw-public-panel"><Boxes aria-hidden="true"/><h3>Check what you own.</h3><p>Look at the actual primitive output, access, conditions, and sources. Descriptions can be unfinished or purely narrative. Reusing an owned character primitive in a capability does not purchase it again.</p></article><article className="sw-public-panel"><BookOpen aria-hidden="true"/><h3>Find the relevant numbers.</h3><p>Use the sheet’s practices, DCs, modifiers, and Vitality when the agreed resolution calls for them. Record consequences so the next action starts from the changed state.</p></article><article className="sw-public-panel"><Swords aria-hidden="true"/><h3>Keep the ruling at the table.</h3><p>Use the guidance for scaling and resolution as a reference. Your GM decides feasibility, ambiguity, and how the scene changes; an editor selection does not settle those questions by itself.</p></article></div></section>
    <section className="sw-public-section" aria-labelledby="next-title"><header className="sw-public-section-head"><div><p className="sw-public-kicker">Your turn</p><h2 id="next-title">Who will you bring?</h2></div><p>A very different existing character, Futoshi, begins with disciplined weapon training and a mind strengthened by emotion. The same process can express a very different person.</p></header><div className="sw-public-actions"><Link className="sw-cta-primary" href="/characters/new">Create your foundation <ArrowRight aria-hidden="true"/></Link><Link className="sw-cta-ghost" href="/combat">Follow a combat round <Swords aria-hidden="true"/></Link><Link className="sw-cta-ghost" href="/library">Read the Library <BookOpen aria-hidden="true"/></Link><Link className="sw-public-link" href="/atelier">Compose in the Atelier <Hammer aria-hidden="true"/></Link></div></section>
  </div>
</div>;}
