import { privateJson } from "@/lib/http/private-json";
import {readBoundedJson,RequestSizeError} from "@/lib/http/read-bounded-json";
import {monsterPreviewInput} from "@/lib/monsters/draft";
import {shuffleMonster} from "@/lib/monsters/shuffle";
import { auth } from "@clerk/nextjs/server";
import { db } from "@/db/client";
import { monsterCopies } from "@/db/schema/monsters";
import { eq } from "drizzle-orm";
import { createMonster,listMonsters,prepareMonster,visibleMonster } from "@/lib/monsters/service";
export async function GET(request:Request) { const {userId}=await auth(); return privateJson({ monsters:await listMonsters(userId,Math.max(0,Math.min(1000000,Math.floor(Number(new URL(request.url).searchParams.get("offset"))||0)))), copies:userId ? await db.select().from(monsterCopies).where(eq(monsterCopies.userId,userId)).limit(100) : [] }); }
export async function POST(request:Request) { const {userId}=await auth(); if(!userId)return privateJson({error:"Sign in to create monsters."},{status:401}); try { const body=await readBoundedJson(request,1_048_576) as {definition:unknown;forkedFromId?:string;shuffle?:boolean;preview?:boolean;locks?:unknown[];shuffleKinds?:("PRIMITIVE"|"CAPABILITY")[];shuffleBudget?:number;isPublic?:boolean;sourceCollectionId?:string|null;visibility?:"PUBLIC"|"PRIVATE"|"FOLLOWERS_ONLY"}; if(body.shuffle)return privateJson(await shuffleMonster(body.definition,userId,Array.isArray(body.locks)?body.locks.filter((l:unknown)=>typeof l==="string"):[],{...(body.shuffleKinds!==undefined?{shuffleKinds:body.shuffleKinds}:{}),...(body.shuffleBudget!==undefined?{shuffleBudget:body.shuffleBudget}:{})})); if(body.preview)return privateJson(await prepareMonster(monsterPreviewInput(body.definition),userId)); if(body.forkedFromId&&!await visibleMonster(body.forkedFromId,userId))return privateJson({error:"Fork source not found."},{status:404}); return privateJson(await createMonster(userId,body.definition,body.isPublic===true,body.forkedFromId,body.sourceCollectionId,typeof body.visibility==="string"&&["PUBLIC","PRIVATE","FOLLOWERS_ONLY"].includes(body.visibility)?body.visibility:undefined),{status:201}); }catch(e){return privateJson({error:e instanceof Error?e.message:"Invalid monster."},{status:e instanceof RequestSizeError?413:400});} }
