import { LibraryRefresh } from "@/components/library-refresh";
import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { Magra, Teko } from "next/font/google";
import Script from "next/script";
import { ClerkProvider } from "@clerk/nextjs";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { AppShell } from "@/components/layout/app-shell";
import { FullscreenInit } from "@/components/layout/fullscreen-init";
import "./globals.css";
import "./v12.css";

// Retain the previous typefaces behind the data-ui switch so setting
// NEXT_PUBLIC_SW_UI_VERSION=legacy is a complete visual rollback.
const legacyDisplay = Teko({
  subsets: ["latin"],
  variable: "--font-sword-display-legacy",
  weight: ["400", "700"],
});

const legacyBody = Magra({
  subsets: ["latin"],
  variable: "--font-sword-body-legacy",
  weight: ["400", "700"],
});

const unicaOne = localFont({
  src: "./fonts/unica-one-400-latin-f1708315.woff2",
  variable: "--font-v12-title",
  weight: "400",
  display: "swap",
});

const oxanium = localFont({
  src: "./fonts/oxanium-500-latin-320e2c0e.woff2",
  variable: "--font-v12-subtitle",
  weight: "500",
  display: "swap",
});

const aubrey = localFont({
  src: "./fonts/aubrey-400-latin-e006e0e2.woff2",
  variable: "--font-v12-body",
  weight: "400",
  display: "swap",
});

const syne = localFont({
  src: "./fonts/syne-600-latin-48dc6652.woff2",
  variable: "--font-v12-system",
  weight: "400 800",
  display: "swap",
});

const ibmPlexMono = localFont({
  src: [
    { path: "./fonts/ibm-plex-mono-400-latin-bc87d8e0.woff2", weight: "400" },
    { path: "./fonts/ibm-plex-mono-500-latin-a80b2cab.woff2", weight: "500" },
    { path: "./fonts/ibm-plex-mono-600-latin-2137a53a.woff2", weight: "600" },
  ],
  variable: "--font-v12-technical",
  display: "swap",
});

// Next.js 16: themeColor moved out of metadata. Putting it in metadata
// triggers "Unsupported metadata themeColor is configured in metadata
// export" on every route. Viewport exports go to a <meta name="viewport">
// tag instead, which is where the browser actually reads theme-color from.
export const metadata: Metadata = {
  title: "SwordWeave",
  description: "Open-source web engine for the SwordWeave TTRPG system.",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "SwordWeave",
  },
};

export const viewport: Viewport = { themeColor: "#0b0a0f" };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        {/* Logo assets shipped 2026-07-14 in public/: logo-light.png
            (teal-on-transparent, light-mode brand mark), logo-dark.png
            (white-on-transparent, dark-mode brand mark). favicon-source
            is the white-bg + teal-mark source for browser/PWA icons.

            Theme-preferred favicon: we ship BOTH the white-bg AND
            dark-bg variants. Browsers with dark-mode tab chrome
            (iOS Safari dark, Chrome dark, Firefox dark) pick the
            `media="(prefers-color-scheme: dark)"` link, light-mode
            browsers pick the no-media version. Both reduce the
            visual conflict between a white-favicon-bg and a dark
            browser-chrome.

            Both favicons are 16/32/48 multi-frame .ico files
            generated by Pillow from the dark-bg source. Light-bg
            logo is also referenced as the brand mark on the homepage
            hero and the FAB speed-dial "Home" entry. */}
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link
          rel="icon"
          href="/favicon-dark.ico"
          sizes="any"
          media="(prefers-color-scheme: dark)"
        />
        <link
          rel="apple-touch-icon"
          href="/apple-touch-icon.png"
          sizes="180x180"
        />
        {/* Phase 18J (2026-07-14, perf): preload Clerk's browser
            bundle. Verified by inspecting /sandbox/grammar's <head>
            on production: Clerk preloads `ui.browser.js` but injects
            `clerk.browser.js` as a <script async> LATE in the HTML
            (after ~15 Next chunks). The browser can't fetch
            clerk.browser.js until it parses that late <script>, which
            adds ~200-400ms of serial delay on Slow 4G real-user
            mobile. With this link rel=preload, the browser starts
            fetching clerk.browser.js in parallel with the very first
            Next chunk. The crossorigin attribute matches Clerk's
            `<script crossorigin="anonymous">` declaration so the
            preload resolves to the same cache entry as the script.

            Why this URL is stable: `clerk.swordweave.quest` is our
            Clerk proxy subdomain (your account's instance URL); the
            /npm path is what `@clerk/nextjs` injects across all v6
            versions. Major-version bumps update the path; we'd notice
            via 404s in browser console after a Vercel deploy and
            update this. */}
        <link
          rel="preload"
          href="https://clerk.swordweave.quest/npm/@clerk/clerk-js@6/dist/clerk.browser.js"
          as="script"
          crossOrigin="anonymous"
        />
        {/* Phase 18F (2026-07-14, perf): early-connect hints for
            third-party origins that gate the LCP path.

            Why each one matters:
            - clerk.swordweave.quest: Clerk's client bundle
              (clerk.browser.js + clerk-ui) is render-blocking for
              any signed-in route. Without preconnect the browser
              doesn't even START the DNS/TLS handshake until it
              sees a <script src=> pointing at it, adding ~150ms
              on Slow 4G. Three of them: dns-prefetch (cheap, runs
              in parallel), preconnect (does full handshake but
              parallelized with the rest of the HTML parse),
              preload (no — we don't preload because we don't know
              which Clerk script the user needs yet).
            - cdn.jsdelivr.net: the game-icons.net SVGs are proxied
              through jsDelivr's GitHub mirror at first-paint when
              a row of icons becomes visible (lazy-img under the
              fold). Preconnecting warms the connection so the first
              scroll triggers IO with no RTT penalty.
            - fonts.gstatic.com + fonts.googleapis.com: Teko and
              Magra come from next/font/google, which already
              self-hosts via next/font's optimization. The browser
              only ever contacts our domain for the static font
              files, so we don't need a hint here. Documented for
              the next person who reads this comment.

            Why we don't use crossOrigin="anonymous": preconnect
            without crossOrigin does the bare TCP/TLS handshake,
            which is the slow part. The actual GET comes later and
            will add its own headers if needed.
        */}
        <link rel="dns-prefetch" href="https://clerk.swordweave.quest" />
        <link rel="preconnect" href="https://clerk.swordweave.quest" />
        <link rel="dns-prefetch" href="https://cdn.jsdelivr.net" />
        <link rel="preconnect" href="https://cdn.jsdelivr.net" />
      </head>
      <body
        data-ui={process.env["NEXT_PUBLIC_SW_UI_VERSION"] ?? "v12"}
        className={`${legacyDisplay.variable} ${legacyBody.variable} ${unicaOne.variable} ${oxanium.variable} ${aubrey.variable} ${syne.variable} ${ibmPlexMono.variable}`}
      >
        <Script id="swordweave-theme" strategy="beforeInteractive">
          {`
try {
  const storedTheme = window.localStorage.getItem("swordweave-theme");
  const legacyTheme = window.localStorage.getItem("sw-dark-mode");
  const useLight = storedTheme === "light" || (!storedTheme && legacyTheme === "0");
  document.documentElement.classList.toggle("dark", !useLight);
} catch {}
          `}
        </Script>
        <ClerkProvider
          signInUrl="/sign-in"
          signUpUrl="/sign-up"
          signInFallbackRedirectUrl="/atelier"
          signUpFallbackRedirectUrl="/atelier"
        >
          <FullscreenInit />
          <AppShell><LibraryRefresh />{children}</AppShell>
          {/* Vercel Web Analytics — tracks pageviews, custom events,
              and visitors. Per
              https://vercel.com/docs/analytics/quickstart?framework=nextjs,
              the Analytics component auto-handles route changes via
              the App Router. Drop it anywhere in the tree; we put it
              next to AppShell so it shares the clerk+theme context. */}
          <Analytics />
          {/* Vercel Speed Insights — tracks Core Web Vitals on real
              visits. Per
              https://vercel.com/docs/speed-insights/quickstart,
              the SpeedInsights component ships a tiny client script
              that records LCP/CLS/INP and reports them to the
              project's Speed Insights dashboard. Next.js v13.5+
              must use the /next subpath import (not /react) — the
              docs call this out explicitly because the /react
              subpath bypasses Next's app-router route detection. */}
          <SpeedInsights />
        </ClerkProvider>
      </body>
    </html>
  );
}
