import Link from "next/link";
import { ArrowRight, BookOpen, Compass, Gem, Layers3, ShieldHalf, Sparkles, Swords } from "lucide-react";
import type { Metadata } from "next";
import { PublicNav } from "@/components/home/public-nav";
import { cumulativeBuForLevel, maxBuDebtForLevel } from "@/lib/engine/bu";
import { computeMaxVitality } from "@/lib/engine/vitality";
import { proficiencyBonus } from "@/lib/engine/practices";

export const metadata: Metadata = {
  title: "Create your character · SwordWeave",
  description: "Bring the character in your head to the table. A practical guide to attributes, Build Units, reusable rules, and meaningful drawbacks.",
};
const LEVELS = [1,2,3,4,5,6,7,8,9,10,13,17,21,25,29];
const CHOICES = [
  {icon:Compass,title:"Give them a life.",body:"Give them a name and a short idea of who they are. Quickbuild offers ready lineage, upbringing and manifest choices. Complete character offers more space for their story. Both produce a sheet you can keep developing."},
  {icon:Gem,title:"Choose a foundation.",body:"Distribute 10 points across Physical, Mental, and Magical. Each score can range from −1 to 5. Choose a specialty, then review the related practices and saves on your sheet."},
  {icon:Layers3,title:"Buy the pieces you need.",body:"Choose your character’s domain and verb access through a heritage or starting package. Touch range and 1d4 are free baselines when that category is absent. Optional drawbacks give credit with a real consequence; items have a separate allowance. Leave some BU for discoveries during play."},
  {icon:Swords,title:"Compose something memorable.",body:"Ready capabilities are convenient saved ideas. You can also assemble an action from owned primitives during play and save it later. Purchase or invent a missing piece using spare BU when it fits the scene and the DM agrees, even during combat."},
];

export default function CharacterPage(){return <div className="sw-home sw-public-site sw-public-site--arcane sw-character-guide">
  <PublicNav />
  <div id="main-content">
    <header className="sw-public-hero sw-public-hero--compact sw-character-guide__hero"><div><p className="sw-public-kicker"><Sparkles aria-hidden="true"/> The character forge</p><h1 className="sw-public-title">Bring someone<br /><em>only you could imagine.</em></h1><p className="sw-public-deck">A mapmaker who folds roads. A knight who bargains with echoes. A cook who keeps a small thunderstorm in a jar. Start there. Build the rules around them.</p><div className="sw-public-actions"><Link className="sw-cta-primary" href="/characters/new">Create your character <ArrowRight aria-hidden="true"/></Link><a className="sw-cta-ghost" href="#build-example">See a build take shape <Layers3 aria-hidden="true"/></a></div></div><aside className="sw-character-package" aria-label="Example character package"><span className="sw-public-kicker">An illustrative character / connected pieces</span><h2>Lyra, the wayfinder</h2><p>A mine runner who always looks for another way out.</p><div className="sw-character-package__roots"><span><small>Lineage</small>Saltborn</span><span><small>Upbringing</small>Mine runner</span><span><small>Manifest</small>Wayfinder</span></div><div className="sw-character-package__capability"><Layers3 aria-hidden="true"/><span><small>Capability</small>A Way Out</span></div><ul><li><Gem aria-hidden="true"/><span>Stride Extension<small>Move faster over land</small></span></li><li><Gem aria-hidden="true"/><span>Aquatic Unlock<small>Swim at your land speed</small></span></li><li><Gem aria-hidden="true"/><span>Subterranean Bore<small>Burrow through soft earth</small></span></li></ul><a className="sw-public-link" href="#build-example">Open the package <ArrowRight aria-hidden="true"/></a></aside></header>

    <section className="sw-public-section" aria-labelledby="choices-title"><header className="sw-public-section-head"><div><p className="sw-public-kicker">01 / From a person to a sheet</p><h2 id="choices-title">Four choices.<br /><em>Room to become more.</em></h2></div><p>You do not need a finished build before you begin. Establish a foundation, keep some points available, and return to the workshop as the character grows.</p></header><div className="sw-public-grid">{CHOICES.map((choice,i)=><article className="sw-public-panel" key={choice.title}><choice.icon aria-hidden="true"/><span className="sw-public-number">0{i+1}</span><h3>{choice.title}</h3><p>{choice.body}</p></article>)}</div></section>

    <section id="build-example" className="sw-public-section" aria-labelledby="example-title"><header className="sw-public-section-head"><div><p className="sw-public-kicker">02 / A character is a package</p><h2 id="example-title">A life becomes a build.<br /><em>Every piece has a place.</em></h2></div><p>Follow Lyra’s idea into a concrete composition. Her heritage names and capability are examples; the three primitive ingredients below are existing Library rules.</p></header>
      <div className="sw-character-composition">
        <article className="sw-public-panel"><Compass aria-hidden="true"/><p className="sw-public-kicker">01 / Concept</p><h3>She finds a way out.</h3><p>Lyra grew up around flooded salt workings. She became the runner sent ahead when a passage collapsed. Now she wants to guide others to safety.</p></article>
        <article className="sw-public-panel"><p className="sw-public-kicker">02 / Heritage</p><h3>Give that history a home.</h3><dl className="sw-character-composition__heritage"><div><dt>Lineage · Saltborn</dt><dd>Her inherited adaptation to saltwater and underground life.</dd></div><div><dt>Upbringing · Mine runner</dt><dd>Her training, routes, and years underground.</dd></div><div><dt>Manifest · Wayfinder</dt><dd>The path she chooses: becoming someone others can follow. Place the capability here.</dd></div></dl></article>
        <article className="sw-public-panel"><Layers3 aria-hidden="true"/><p className="sw-public-kicker">03 / Capability inside Manifest</p><h3>A Way Out</h3><p>A named collection of Lyra’s movement rules. She can run, swim, or burrow where those rules permit. The name makes the pieces easy to find during play.</p><p>Compose these primitives directly into the capability. An effect is optional: use one when a group of rules should be a reusable subassembly.</p></article>
      </div>
      <div className="sw-character-ingredients"><header><p className="sw-public-kicker">04 / The actual primitive ingredients</p><h3>Open the capability. See the rules.</h3></header><div className="sw-public-grid">
        <article><Gem aria-hidden="true"/><h4>Stride Extension</h4><p>Adds 10 feet to baseline Land Speed.</p></article>
        <article><Gem aria-hidden="true"/><h4>Aquatic Unlock</h4><p>Grants Swim Speed equal to baseline Land Speed.</p></article>
        <article><Gem aria-hidden="true"/><h4>Subterranean Bore</h4><p>Grants a 15-foot Burrow Speed through soft earth or sand.</p></article>
      </div><p>These are movement permissions, not a promise that every escape works. Soft earth is not solid rock; moving yourself does not automatically move a whole group. Read each current Library definition and agree the situation with your GM.</p><div className="sw-public-example"><span className="sw-public-kicker">At the table</span><p>“The tunnel is flooded. I swim ahead to see whether that side passage still reaches the surface.”</p></div></div>
      <p className="sw-character-guide__note">Your character pays for the owned primitive rules. Reusing those same rules in another capability does not charge their progression cost again. Heritage and capability names do not grant extra mechanics. Items have their own accounting. Range and dice type are owned permissions; using a broader or more complex expression can still increase the action’s pressure and cost.</p><div className="sw-public-actions"><Link className="sw-cta-ghost" href="/library">Read the current rules and costs <ArrowRight aria-hidden="true"/></Link><Link className="sw-public-link" href="/atelier">Compose your own package <Layers3 aria-hidden="true"/></Link></div>
    </section>

    <section className="sw-public-section" aria-labelledby="mirror-title"><div className="sw-public-duet"><article className="sw-public-panel"><ShieldHalf aria-hidden="true"/><p className="sw-public-kicker">03 / Strength with a cost</p><h2 id="mirror-title">A weakness should<br /><em>change how you play.</em></h2><p>Mirroring an eligible rule gives the build a real drawback and the credit shown for that rule. Read the mirrored result before accepting it.</p><p>Owning an eligible primitive lets you use either direction within an action or composition without purchasing it twice. A mirrored drawback still has its accepted personal consequence: directing a positive effect elsewhere does not silently remove that drawback from your sheet. Agree targets, duration, access, resolution and costs.</p></article><article className="sw-public-panel"><p className="sw-public-kicker">Drawback ceiling</p><h3>There is a limit.</h3><table className="sw-public-ledger"><caption>Maximum drawback credit by level bracket</caption><thead><tr><th scope="col">Levels</th><th scope="col">Credit limit</th></tr></thead><tbody>{[1,5,9,13,17].map(level=><tr key={level}><th scope="row">{level}–{level+3}</th><td>{maxBuDebtForLevel(level)} BU</td></tr>)}</tbody></table><p>Choose drawbacks that fit the character. The sheet checks the ceiling when you apply a draft. A descriptive flaw can remain part of the story without becoming a purchased drawback.</p></article></div></section>

    <section className="sw-public-section" aria-labelledby="growth-title"><header className="sw-public-section-head"><div><p className="sw-public-kicker">04 / A growing character</p><h2 id="growth-title">The budget grows.<br /><em>The person changes.</em></h2></div><p>For a first adventure, ask the DM whether level 3–6 would give you useful room to experiment; experienced roleplayers may prefer level 10. Levels are a suggested pace and a reference for progression. There is no level-20 cap: the same progression rules continue beyond it. Your table can use a custom starting budget or DM adjustments. The DM awards BU whenever appropriate. Ordinary progression steps add 10 BU, with larger increases after each four-level bracket; the table below already includes those bonuses.</p></header><p className="sw-character-guide__note">Base Max Vitality = (10 + Proficiency Bonus) × level, before primitive or other modifiers. All values below come from the character sheet’s progression functions.</p><p className="sw-character-guide__scroll-hint">On a small screen, scroll the table sideways to see every column.</p><div className="sw-character-guide__table" tabIndex={0} role="region" aria-label="Character progression table"><table className="sw-public-ledger"><caption>Selected progression levels, continuing beyond 20</caption><thead><tr><th scope="col">Level</th><th scope="col">Base BU</th><th scope="col">Proficiency</th><th scope="col">Base Max Vitality</th><th scope="col">Drawback limit</th></tr></thead><tbody>{LEVELS.map(level=><tr key={level}><th scope="row">{level}</th><td>{cumulativeBuForLevel(level)}</td><td>+{proficiencyBonus(level)}</td><td>{computeMaxVitality(level)}</td><td>{maxBuDebtForLevel(level)} BU</td></tr>)}</tbody></table></div><div className="sw-public-actions"><Link className="sw-cta-primary" href="/characters/new">Give them a character sheet <ArrowRight aria-hidden="true"/></Link><Link className="sw-cta-ghost" href="/combat">Take them into a scene <Swords aria-hidden="true"/></Link><Link className="sw-public-link" href="/start">Read the walkthrough <BookOpen aria-hidden="true"/></Link></div></section>
  </div>
</div>;}
