/** Small, freely extensible heritage bundles. Original prose; no level gates. */
export type EarlyBase = {kind:"LINEAGE"|"UPBRINGING"|"MANIFEST";name:string;parent:string;bu:number;description:string;primitives:string[];capabilities:string[];iconKey:string;traits:string};
export const earlyHeritageBases:EarlyBase[]=[
 {kind:"LINEAGE",name:"Hearthspark",parent:"Flintskin",bu:6,description:"Hearthsparks carry warm flecks of mineral under their skin. A struck knuckle can spark prepared tinder; a stubborn, compact body gives them a little extra endurance. Their spark needs fuel and air and grants no protection from fire.",primitives:["Vitality Core Augment I"],capabilities:["Tinder Spark"],iconKey:"delapouite/flint-spark",traits:"Flecked skin; a practiced tinder ritual; a preference for warm stone."},
 {kind:"LINEAGE",name:"Duskling",parent:"Nightpupil",bu:6,description:"Dusklings have wide pupils and fine, light-sensitive lashes. They read movement in dim natural light and train their attention on small changes. Total darkness still hides the world from them.",primitives:["Dim-Light Acuity","Awareness Check +1"],capabilities:[],iconKey:"delapouite/night-vision",traits:"Wide pupils; dusk routines; curiosity about small movements."},
 {kind:"LINEAGE",name:"Griproot",parent:"Forestkind",bu:6,description:"Griproots have gripping pads along fingers and toes, an inheritance suited to bark and rough masonry. Their climbing technique helps them follow a real surface; adhesion does not create a path through empty air or free them from the surface's limits.",primitives:["Adhesive Grip","Fieldcraft Check +1"],capabilities:[],iconKey:"cathelineau/tree-face",traits:"Textured fingertips; quiet branch walks; a favorite climbing tree."},
 {kind:"LINEAGE",name:"Whispercolony",parent:"Sporeveil",bu:7,description:"Whispercolonies carry subtle scent glands and an instinct for colony rhythms. They send brief messages to people who know the scent code and watch their surroundings carefully. Wind, distance, and barriers can break a message; the scent does not compel anyone.",primitives:["Awareness Proficiency"],capabilities:["Colony Message"],iconKey:"delapouite/mushrooms-cluster",traits:"A familiar scent signature; a home colony; expressive antenna-like hair."},
 {kind:"LINEAGE",name:"Glidesprout",parent:"Hollowbone",bu:7,description:"Glidesprouts unfold small membranes between light limbs to steer a descent. Their frame has enough resilience to weather a hard journey. A glide requires height and a viable landing route; these membranes do not grant powered flight or hovering.",primitives:["Vitality Core Augment +5"],capabilities:["Wing-Catch Descent"],iconKey:"delapouite/hang-glider",traits:"Folded membranes; a love of high overlooks; deliberate landings."},
 {kind:"LINEAGE",name:"Reachling",parent:"Longreach",bu:6,description:"Reachlings have flexible joints that stretch a hand toward a nearby ledge or across a modest gap. A careful eye guides delicate retrieval. This reach helps manipulation; it does not extend weapon attacks or the range of a purchased capability.",primitives:["Finesse Check +1"],capabilities:["High-Ledge Recovery"],iconKey:"delapouite/arm",traits:"Long fingers; flexible posture; a habit of fetching things for others."},
 {kind:"UPBRINGING",name:"Roadside Errand Runner",parent:"Wanderer",bu:4,description:"Short deliveries taught you to leave recognizable marks and check your route before setting out. Your signs help someone who knows the code retrace a path until weather, traffic, or changed terrain removes them.",primitives:["Durable Route Marking","Fieldcraft Check +1"],capabilities:[],iconKey:"delapouite/road",traits:"An old delivery satchel; a familiar route; someone awaiting a message."},
 {kind:"UPBRINGING",name:"Workshop Sweeper",parent:"Tinkerer",bu:6,description:"You learned by sorting scraps and watching tools fail. With suitable material and time, you can patch a small ordinary object for one stated task. Your practical knowledge helps assess the work; a patch remains limited by material and load.",primitives:["Knowledge Check +1"],capabilities:["Patch the Seam"],iconKey:"darkzaitzev/big-gear",traits:"A box of useful offcuts; a former teacher; a tool you hope to own."},
 {kind:"UPBRINGING",name:"Lantern Stall Helper",parent:"Festival Lantern Tender",bu:4,description:"Setting out festival lanterns taught you a rehearsed visual code and the patience to watch a crowd. You can communicate simple signals to observers who can see and understand them, using an actual light or visible gesture.",primitives:["Visible Signal Code","Awareness Check +1"],capabilities:[],iconKey:"lorc/lantern",traits:"A favored lantern color; a remembered festival; a rehearsed signal."},
 {kind:"UPBRINGING",name:"Orchard Neighbor",parent:"Orchard Tender",bu:6,description:"Seasonal work among fruit trees taught you fieldcraft and ordinary grafting. You can join compatible living stock with suitable tools and care. The graft develops over time and depends on soil, weather, and the plant's health.",primitives:["Plant Grafting","Fieldcraft Proficiency"],capabilities:[],iconKey:"delapouite/fruit-tree",traits:"A family orchard; a grafting knife; a tree planted for someone."},
 {kind:"UPBRINGING",name:"Agreement Recorder",parent:"Witness Scribe",bu:6,description:"You helped preserve promises exactly as people spoke them. You can record voluntary testimony and use learned reasoning to compare its terms. The record preserves words without proving their truth or forcing compliance.",primitives:["Exact Testimony Record","Reason Proficiency"],capabilities:[],iconKey:"delapouite/scroll-quill",traits:"A careful script; a memorable agreement; a person who trusts your record."},
 {kind:"UPBRINGING",name:"Harbor Rope Hand",parent:"Quarry Rigger",bu:8,description:"Loading boats taught you to fasten a sound safety line and work ordinary counterweights. Your lifts and catches use real ropes, supports, length, and load limits. Every anchor needs a place that can bear the force.",primitives:["Rigged Counterweight"],capabilities:["Line Catch"],iconKey:"lorc/stone-block",traits:"Callused hands; a reliable knot; a crew you once worked with."},
 {kind:"MANIFEST",name:"Steady Blade",parent:"Striker",bu:8,description:"Your emerging build centers on one controlled, driving blow and reliable aim. Choose the weapon and style that express it. Attack modifiers appear on your sheet; the blow's fictional outcome follows the purchased capability and the resolved action.",primitives:["Precise Vector Alignment (Global Attack Modifier)"],capabilities:["Driving Blow"],iconKey:"lorc/sword-spade",traits:"A deliberate stance; a favored ordinary weapon; a signature direct approach."},
 {kind:"MANIFEST",name:"Doorwatch",parent:"Guardian",bu:7,description:"You build around being difficult to move when a passage matters. A braced position supports a relevant physical save, backed by a small general saving throw improvement. Call the position when you actually hold it; this build grants no automatic interception or extra action.",primitives:["Physical Saving Throw +1","Braced Position"],capabilities:[],iconKey:"sbed/shield",traits:"A protective habit; a place you once defended; a measured stance."},
 {kind:"MANIFEST",name:"Quickstep",parent:"Skirmisher",bu:9,description:"You combine a longer walking stride with a dependable driving attack. Speed helps you choose an angle along legal terrain. Neither movement nor the attack grants an additional turn or bypasses an obstacle by itself.",primitives:["Stride Extension"],capabilities:["Driving Blow"],iconKey:"lorc/dodging",traits:"Light footwork; a preferred approach angle; a practiced retreat route."},
 {kind:"MANIFEST",name:"Glimmer Caller",parent:"Mystic",bu:8,description:"Your first magical specialty is a visible Light signal shaped into a field beacon. Purchased Light access and a rehearsed code provide the foundation, with a small Mysticism check improvement. Observers must still see the beacon and know its meaning.",primitives:["Mysticism Check +1"],capabilities:["Field Beacon"],iconKey:"lorc/magic-swirl",traits:"A beacon pattern; a chosen light hue; a person who knows your signals."},
 {kind:"MANIFEST",name:"Stitchkeeper",parent:"Field Medic",bu:6,description:"You train in small, practical interventions: splinting an injury, restoring a little Vitality, and understanding the supplies in your kit. Resolve the treatment's output and enter healing through the sheet's Vitality control. This is a beginning in care, with room for stronger treatments later.",primitives:["Knowledge Check +1"],capabilities:["Splint and Rally"],iconKey:"sbed/medical-pack-alt",traits:"A tidy treatment kit; a careful bedside habit; someone you once helped."},
 {kind:"MANIFEST",name:"Patchwright",parent:"Artificer",bu:8,description:"You develop through making damaged equipment useful again for a particular job. Stronger practical knowledge supports a temporary material patch. Suitable supplies and several minutes of access are required; the patch does not become a complete repair or an unlimited enchantment.",primitives:["Knowledge Check +2"],capabilities:["Patch the Seam"],iconKey:"darkzaitzev/big-gear",traits:"A portable work roll; an inventive repair; a favorite salvage material."},
];
