/** Private examples with deliberate unspent room. No mirrors or automatic condition claims. */
export type DemoCharacter = {key:string;name:string;budget:number;level:number;attributes:[number,number,number];proficient:'PHYSICAL'|'MENTAL'|'MAGICAL';heritages:string[];capabilities:string[];primitives:string[];items:{name:string;equipped:boolean}[];concept:string};
export const demoCharacters:DemoCharacter[]=[
 {key:'25-blade',name:'Demo · 25 BU · Hearth Road Blade',budget:25,level:1,attributes:[5,3,2],proficient:'PHYSICAL',heritages:['Hearthspark','Steady Blade'],capabilities:[],primitives:['Domain of Motion','Verb Access Tier I','Touch Range','Standard Die Block (1d6)'],items:[{name:'Ledgerguard Saber',equipped:true},{name:'Patchplate Vest',equipped:true}],concept:'A mineral-skinned courier learning one dependable melee strike. The package buys Motion, Tier I, touch delivery and d6 output. Fire sparks are a contextual permission, not fire immunity.'},
 {key:'25-beacon',name:'Demo · 25 BU · Dusk Lantern Caller',budget:25,level:1,attributes:[2,3,5],proficient:'MAGICAL',heritages:['Duskling','Lantern Stall Helper','Glimmer Caller'],capabilities:[],primitives:['Verb Access Tier I','Touch Range','Standard Die Block (1d6)'],items:[{name:'Splitgrip Staff',equipped:true},{name:'Boundary Marker Satchel',equipped:true}],concept:'A quiet lookout using a Light beacon and dim-light vision. The beacon already supplies the Light domain. Output is rolled and any Vitality change entered manually.'},
 {key:'50-guard',name:'Demo · 50 BU · Harbor Doorwatch',budget:50,level:3,attributes:[5,3,2],proficient:'PHYSICAL',heritages:['Griproot','Harbor Rope Hand','Doorwatch'],capabilities:['Shielded Passage'],primitives:['Domain of Motion','Verb Access Tier I','Touch Range','Heavy Die Block (1d8)','Vitality Core Augment +10','Focused Presence (Global DC Modifier)'],items:[{name:'Ledgerguard Saber',equipped:true},{name:'Doorbrace Shield',equipped:true},{name:'Patchplate Vest',equipped:true},{name:'Rescue Line Spool',equipped:true}],concept:'A rope-trained guard who holds a prepared passage. The shielded-passage condition belongs to its primitive and must be switched on only while its authored situation holds.'},
 {key:'50-surveyor',name:'Demo · 50 BU · Orchard Surveyor',budget:50,level:3,attributes:[3,5,2],proficient:'MENTAL',heritages:['Whispercolony','Roadside Errand Runner','Patchwright'],capabilities:['Measured Survey'],primitives:['Domain of Wood','Verb Access Tier I','Touch Range','Minor Die Block','Fieldcraft Check +3'],items:[{name:'Splitgrip Staff',equipped:true},{name:'Patchsmith Roll',equipped:false},{name:'Boundary Marker Satchel',equipped:true}],concept:'A scent-speaking repairer who maps routes and tends living wood. Measured Survey uses its prepared survey-tool condition. Mapping, grafting and patching follow their stated material and time limits.'},
 {key:'100-medic',name:'Demo · 100 BU · Ashlung Stitch Medic',budget:100,level:8,attributes:[3,5,2],proficient:'MENTAL',heritages:['Ashlung','Field Surgeon Apprentice','Thread Surgeon'],capabilities:['Dose and Release','Gentle Treatment'],primitives:['Verb Access Tier I','Touch Range','Heavy Die Block (1d8)','Knowledge Check +PB','Mental Saving Throw +2','Carry Capacity Augment +20'],items:[{name:'Patchsmith Roll',equipped:false},{name:'Boundary Marker Satchel',equipped:true},{name:'Patchplate Vest',equipped:true}],concept:'A field medic with smoke filtration, trained triage and reusable treatment recipes. Stored remedies need their actual supplies; healing is resolved and entered through Vitality controls.'},
 {key:'100-scout',name:'Demo · 100 BU · Canopy Ground Scout',budget:100,level:8,attributes:[5,3,2],proficient:'PHYSICAL',heritages:['Forestkind',"Smuggler's Lookout",'Veil Runner'],capabilities:['Groundline Scout','Dry Wall Traverse'],primitives:['Domain of Motion','Verb Access Tier I','Near Range','Standard Die Block (1d6)','Awareness Check +PB','Swimming Speed +10'],items:[{name:'Survey Bow',equipped:true},{name:'Rescue Line Spool',equipped:true},{name:'Patchplate Vest',equipped:true}],concept:'A canopy scout who combines still camouflage, prepared routes and contact listening. Camouflage is conditional concealment, not an automatic universal invisible condition. Climbing and swimming retain terrain limits.'},
 {key:'200-architect',name:'Demo · 200 BU · Iron Terrain Architect',budget:200,level:16,attributes:[5,2,3],proficient:'PHYSICAL',heritages:['Ironborn','Siege Mason','Terrain Architect'],capabilities:['Shielded Passage','Measured Survey','Drawback Pulse'],primitives:['Verb Access Tier III','Heavy Die Block (1d8)','Attribute Increment +3 Physical','Carry Capacity Augment +100','Equipment Slot Augment +2'],items:[{name:'Doorbrace Shield',equipped:true},{name:'Splitgrip Staff',equipped:true},{name:'Patchplate Vest',equipped:true},{name:'Patchsmith Roll',equipped:false}],concept:'A plated surveyor who develops stone barriers, support rigs and a bounded loose-object pull. Purchased larger verbs do not grant unlimited creation or free action economy. One DC uses the modified Physical attribute.'},
 {key:'200-sky',name:'Demo · 200 BU · Sky Signal Voyager',budget:200,level:16,attributes:[2,3,5],proficient:'MAGICAL',heritages:['Skyborn','Star Surveyor','Mystic'],capabilities:['Drawback Pulse','Forking Lumen','Return-Catch Throw'],primitives:['Verb Access Tier III','Very Far Range','Heavy Die Block (1d8)','Attribute Increment +3 Magical','Magical Saving Throw +5'],items:[{name:'Survey Bow',equipped:true},{name:'Patchplate Vest',equipped:true},{name:'Boundary Marker Satchel',equipped:true}],concept:'A flying Light specialist navigating by stars and signaling over distance. A returning throw needs a legal path and free hand. Forked light splits its output rather than multiplying it; saves and Vitality changes are resolved manually.'},
];
