/** Curated composition data for the 24/48/18 heritage shelf. No DB I/O. */
export type PermissionIdea = { name: string; bu: number; rule: string };
export type EffectIdea = { name: string; text: string; primitives: string[]; target: "self" | "target" | "scene" };
export type CapabilityIdea = { name: string; text: string; primitives: string[]; effects?: string[]; type?: "ACTIVE" | "PASSIVE" | "AUGMENT"; source?: "PHYSICAL" | "MAGICAL" | "PSYCHIC" };
export type HeritageRecipe = { kind: "LINEAGE" | "UPBRINGING" | "MANIFEST"; name: string; primitives: string[]; capabilities: string[] };

// These are narrow fictional permissions. They deliberately have no hard modifier.
// A visible number is provided by a separate numeric primitive when appropriate.
export const permissions: PermissionIdea[] = [
  { name: "Ordinary Smoke Filtration", bu: 4, rule: "Breathe and see sufficiently for ordinary tasks in light nonmagical smoke or ash. Dense smoke still obscures vision; heat, toxic gases, and magical fumes are separate hazards. The table adjudicates exposure." },
  { name: "Water Pressure Sense", bu: 4, rule: "While in connected water, notice nearby pressure changes from a moving body or current. This gives approximate direction, not identity or sight through a sealed barrier." },
  { name: "Slow Facial Reshaping", bu: 6, rule: "Over several minutes, reshape superficial face and skin details without changing mass, size, voice, or clothing. Close inspection may reveal the alteration." },
  { name: "Still-Surface Camouflage", bu: 6, rule: "While motionless against a single surface, slowly match its broad colors and pattern. Movement or a changed backdrop reveals the body; this is not invisibility." },
  { name: "Spark-Shedding Skin", bu: 2, rule: "Strike one's mineral skin against hard stone or metal to produce a small spark. Fuel and air are still needed to ignite anything; this grants no fire resistance." },
  { name: "Soil Disturbance Sense", bu: 4, rule: "With roots or skin touching continuous soil, notice nearby movement in that soil. Gaps, hard floors, and motionless sources prevent this sense." },
  { name: "Electrical Contact Sense", bu: 4, rule: "By touching an uninsulated conductor, notice whether current is present and its rough direction. This does not identify the source or confer resistance." },
  { name: "Dim-Light Acuity", bu: 4, rule: "See ordinary shapes and movement in dim natural light. Total darkness and opaque concealment still block sight." },
  { name: "Controlled Eye Light", bu: 4, rule: "Emit a small visible glow from the eyes for close reading or simple signals. The glow also makes the bearer easier to locate." },
  { name: "Sensitive Branch Feelers", bu: 4, rule: "Probe a reachable small cavity with sensitive branching feelers. They can locate the shape of an unattended object but cannot equip a tool or make an extra attack." },
  { name: "Extended Hand Reach", bu: 4, rule: "Reach across a small gap or up to a nearby ledge with a flexible limb. This does not change capability range, size, or weapon reach." },
  { name: "Soft-Body Compression", bu: 8, rule: "With room to move and without bulky equipment blocking the way, squeeze through an opening that can admit the body's rigid parts. It does not bypass sealed barriers or remove restraints automatically." },
  { name: "Visible Signal Code", bu: 2, rule: "Make simple rehearsed visual signals to observers who can see and know the code. Darkness, cover, distance, and unfamiliar observers can defeat the signal." },
  { name: "Durable Route Marking", bu: 2, rule: "Mark a reachable route with a carried substance or tool. An observer who knows the marks can follow them until they are erased, covered, or the route changes." },
  { name: "Witnessed Mark", bu: 4, rule: "Make a visible mark recording words voluntarily agreed in the witness's presence. It preserves the record but compels nobody and does not detect lies." },
  { name: "Temporary Material Patch", bu: 4, rule: "With suitable carried material and several minutes of access, patch one small ordinary object for a single task. The patch fails under excess load or incompatible material and is not a full repair." },
  { name: "Anchored Safety Line", bu: 4, rule: "Fasten a carried line to a reachable stable anchor and one willing subject or object. The line catches only within its actual length and load; it can be cut or released." },
  { name: "Resonant Alarm", bu: 4, rule: "Prepare a touched rigid object to give a recognizable audible or tactile signal when it is disturbed. State the receiver, transmission path, and when the preparation ends." },
  { name: "Weather Shelter Frame", bu: 4, rule: "Assemble carried material into cover from ordinary rain, wind, or hail for a stated area. It needs space and setup time and does not automatically block attacks." },
  { name: "Breach Survey", bu: 4, rule: "Examine a reachable built structure for a plausible seam, fault, or repair point. The GM describes what inspection can reveal; this does not automatically damage or weaken it." },
  { name: "Small Air Pocket", bu: 8, rule: "Create or preserve a bounded pocket of breathable air using a specified material or domain. State number of users and duration; it is not blanket immunity to gases or drowning." },
  { name: "Animal Signal Reading", bu: 4, rule: "Recognize a trained animal's rehearsed signals and give it simple practiced cues. It remains a separate creature with no free attack or autonomous turn granted by this permission." },
  { name: "Canopy Footing", bu: 4, rule: "Move on reachable living branches that can support the bearer's weight. A gap, rotten limb, slick bark, or great height still calls for the usual movement and checks." },
  { name: "Fine Glasswork", bu: 4, rule: "With tools and material, shape or mend a small glass object during downtime. Heat, time, and breakage risk still matter." },
  { name: "Plant Grafting", bu: 2, rule: "With healthy stock, tools, and time, graft or tend an ordinary plant. Growth is not instant and the result follows the table's environment." },
  { name: "Exact Testimony Record", bu: 2, rule: "Record words heard firsthand in a durable medium with normal time and materials. The record preserves wording, not truth or consent." },
  { name: "Local Weather Reading", bu: 4, rule: "From visible and felt local signs, estimate an approaching ordinary weather change. Sudden magical changes and distant conditions remain uncertain." },
  { name: "Ordinary Lock Familiarity", bu: 4, rule: "Recognize a reachable ordinary lock's type and likely operation. Opening it still needs a key, tools, force, or the normal check." },
  { name: "Careful Body Preparation", bu: 2, rule: "Prepare and preserve a body respectfully with ordinary supplies and time. This grants no healing, resurrection, or supernatural insight." },
  { name: "Structural Stone Shaping", bu: 8, rule: "With stone and a suitable domain/verb, shape a small stable support or section of barrier. The authored capability sets its dimensions, time, and duration." },
  { name: "Kiln-Cured Teeth", bu: 6, rule: "Hardened, heat-tolerant teeth can cut soft metal with sustained chewing and tolerate ordinary hot food. This does not grant a combat damage bonus, armor penetration against a resisting target, or fire resistance." },
  { name: "Spoken Doubt", bu: 6, rule: "Speak a short unsettling phrase to a target that can hear and understand it. The table decides that target's response from the situation; the phrase alone grants no compelled emotion or numeric penalty." },
  { name: "Practiced Aimed Shot", bu: 4, rule: "Take time to aim at a visible target within a range already purchased for the attack. Cover and movement still apply; this permission grants no extra attack or roll bonus." },
  { name: "Driving Strike", bu: 4, rule: "Deliver a direct blow using an attack already available to the character. The chosen weapon or capability sets the damage, range, and target; this permission grants no extra attack or damage." },
  { name: "Animal Messenger Cue", bu: 4, rule: "Give a trained creature a rehearsed cue to carry a simple signal to a known destination. Travel, danger, and the creature's own turn remain at the table; this does not grant a free action." },
  { name: "Braced Position", bu: 4, rule: "Brace at a reachable doorway, edge, or narrow passage using footing and any available anchor. Leaving the stance or location ends the position; the table decides whether a displacement approaches from the defended direction." },
  { name: "Root Feeding", bu: 4, rule: "With living roots in fertile soil and adequate water, draw enough ordinary nourishment to replace a simple meal over several hours. Barren, salted, poisoned, or frozen ground may prevent it; this does not restore Vitality." },
  { name: "Crystal Trace", bu: 6, rule: "With sustained contact, read a recent vibration trace held in the bearer's living crystal. The table describes one rough pattern, direction, or impact; the trace does not preserve words, identity, or a complete memory." },
  { name: "Ferry Passage Reading", bu: 4, rule: "From a known landing, current, and visible markers, judge a safe ordinary ferry crossing. Changed water, hidden hazards, and an unfamiliar boat still require the usual checks." },
  { name: "Unstable Ground Salvage", bu: 4, rule: "Probe a reachable marsh or silt bed and choose a plausible footing or anchor for retrieving one small object. The ground can still collapse, and this grants no extra movement speed." },
  { name: "Water Source Survey", bu: 4, rule: "From local signs and a traveled route, identify a plausible place to search for ordinary water. The table decides whether water exists; this does not create or purify it." },
  { name: "Useful Field Map", bu: 4, rule: "Draw a route map from direct observation with ordinary supplies and time. It preserves observed landmarks until the route changes; it does not reveal unexplored terrain." },
  { name: "Waterproof Message Wrap", bu: 2, rule: "With waxed cloth, resin, or similar carried material, protect one small message from brief immersion. Damage, depth, and prolonged exposure remain possible." },
  { name: "Small Salvage Recovery", bu: 4, rule: "With a line or suitable tool, recover a small unattended object from a reachable flooded or unstable space. Weight, entanglement, visibility, and air remain limits." },
  { name: "Bell Tuning", bu: 4, rule: "With tools, access, and time, tune a metal bell or chime to a recognizable signal. This does not transmit through a disconnected material or compel listeners." },
  { name: "Rigged Counterweight", bu: 4, rule: "With carried rope, pulleys, and a stable anchor, rig a counterweight to move an ordinary load within the equipment's rating. It does not increase the bearer's personal Carry Capacity." },
  { name: "Improvised Rations", bu: 4, rule: "With edible ingredients, fuel, clean water, and time, prepare simple safe portions in a poor camp. This does not create food or neutralize every toxin." },
  { name: "Ledger Trace", bu: 4, rule: "Compare accessible written transactions to find one inconsistency or missing link. Forged records and absent accounts can conceal the trail; this does not reveal a hidden payer automatically." },
  { name: "Hospitality Network", bu: 4, rule: "In a settlement where the bearer has worked, identify a plausible host, supplier, or customary place to ask for shelter. The person remains free to refuse and may demand payment." },
  { name: "Focused Research", bu: 4, rule: "With relevant accessible sources and study time, narrow a question to a useful lead. The table decides what those sources contain; no inaccessible fact is revealed." },
  { name: "Night Sky Route", bu: 4, rule: "With a visible familiar sky and known landmarks, estimate direction and progress at night. Cloud, unfamiliar stars, and changed terrain limit the reading." },
  { name: "Reagent Preparation", bu: 4, rule: "With identified mundane ingredients and tools, prepare a small ordinary salve or test reagent during downtime. Its effect and safety are judged from the ingredients; no healing value is granted by this permission." },
  { name: "Bridge Hazard Call", bu: 4, rule: "From a guarded crossing, call a simple rehearsed warning about a visible load, gap, or approaching hazard. The warning reaches only listeners who can hear and understand it." },
  { name: "Archive Preservation", bu: 4, rule: "With suitable materials and time, stabilize a fragile ordinary document for handling or transport. Lost text is not restored, and a severe tear still needs repair." },
  { name: "Stage Mask Craft", bu: 4, rule: "With tools, material, and fitting time, make a stage mask or ordinary disguise piece. It changes appearance but not body, voice, size, or a close observer's judgment." },
  { name: "Salt Route Hazard Sense", bu: 4, rule: "Recognize familiar signs of dehydration, salt-crusted footing, or depleted stores on a traveled route. This is learned field knowledge, not damage resistance." },
  { name: "Household Count", bu: 4, rule: "Using accessible records and direct visits, identify a discrepancy in a local headcount. Missing or false records limit the answer; this does not locate a person automatically." },
  { name: "Ring Opening Read", bu: 4, rule: "Observe a close opponent's stance in an ordinary bout to identify one plausible opening. The next action still requires its normal roll, and this grants no extra attack." },
  { name: "Portable Lantern Rig", bu: 4, rule: "With a carried lantern, fuel, and mounting gear, position a visible colored signal at a reachable point. The light can be extinguished or obstructed and reveals its own location." },
];

export const effectIdeas: EffectIdea[] = [
  { name: "Brace at the Threshold", target: "self", primitives: ["Braced Position"], text: "The bearer braces a named doorway against displacement from a stated approach. It ends when the stance or doorway is left. A Physical save bonus applies only while a separately purchased bonus is active; this effect has no automatic numeric bonus." },
  { name: "Surveyed Passage", target: "scene", primitives: ["Durable Route Marking"], text: "One route is surveyed and marked before travel until its conditions materially change. The table decides which checks concern that route; this effect has no automatic Fieldcraft bonus." },
  { name: "Tethered Safety", target: "target", primitives: ["Anchored Safety Line"], text: "A willing target is caught by the stated line and anchor if length and load permit. It ends when the line is removed, severed, or released; a hostile restraint is a different effect." },
  { name: "Lantern Signal Found", target: "scene", primitives: ["Visible Signal Code"], text: "A visible signal remains available at a chosen point while its source can be seen. Only observers who know the code understand it; cover or extinguishing ends it." },
  { name: "Resonant Warning", target: "scene", primitives: ["Resonant Alarm"], text: "A prepared rigid object gives one audible or tactile warning when disturbed. Its signal path and duration are chosen during preparation; the table resolves who actually notices it." },
  { name: "Marked Trail", target: "scene", primitives: ["Durable Route Marking"], text: "A specific route carries readable marks until removed, hidden, or the route changes. They do not reveal who followed it or guarantee safe passage." },
  { name: "Witnessed Oath", target: "scene", primitives: ["Witnessed Mark"], text: "Record voluntarily spoken terms and their witnesses. The mark persists until destroyed; it does not compel performance or reveal lies." },
  { name: "Temporary Patch", target: "target", primitives: ["Temporary Material Patch"], text: "One small ordinary object functions for a stated task after being patched with suitable material. It ends when strained beyond its limit or replaced by proper repair." },
  { name: "Hail Shelter", target: "scene", primitives: ["Weather Shelter Frame"], text: "A prepared area shelters occupants from ordinary hail or rain while the frame stands. It gives no automatic DC or damage reduction against attacks." },
  { name: "Held Air", target: "target", primitives: ["Small Air Pocket"], text: "The named subject has a stated pocket of breathable air for one bounded task. It ends when the pocket is spent, opened, or its authored duration passes." },
  { name: "Observed Breach", target: "target", primitives: ["Breach Survey"], text: "A particular object or wall has a plausible seam identified by inspection. The table decides what can exploit or repair it; no automatic damage or DC change is implied." },
  { name: "Mended Vitality", target: "target", primitives: ["Minor Die Block"], text: "A specific treatment may restore 1d4 Vitality to the named target when its capability resolves. The d4 is the purchased output die. Roll and apply Vitality manually; the effect itself does not invoke an automatic healing action." },
  { name: "Harrowing Word", target: "target", primitives: ["Spoken Doubt"], text: "A target that hears and understands a particular unsettling phrase reacts according to the scene. State the phrase and ending event when used. The table decides any consequence; no universal frightened, poisoned, or numerical penalty is assumed." },
  { name: "Stone Barrier", target: "scene", primitives: ["Structural Wall"], text: "The author shapes an available stone section into a bounded barrier with the purchased Stone domain and structure tier. State dimensions, setup, support, and ending condition. The wall blocks passage as its source primitive permits; its durability is decided at the table." },
];

export const capabilityIdeas: CapabilityIdea[] = [
  { name: "Canopy Traverse", primitives: ["Canopy Footing", "Climbing Speed +5"], text: "Cross a reachable sequence of load-bearing branches. Use current climbing movement; unstable branches or gaps require ordinary checks. No teleportation or extra movement is granted." },
  { name: "Current Reading", primitives: ["Water Pressure Sense"], text: "Pause in connected water to sense the rough direction of a nearby moving body or current. The table states range and obstructions; identity remains unknown." },
  { name: "Plate Exchange", primitives: ["Retractable Carapace", "Temporary Material Patch"], effects: ["Temporary Patch"], text: "With spare plate material and several minutes, replace one damaged outer plate. The plate's fictional protection is stated; no automatic DC or Vitality restoration occurs." },
  { name: "Shallow Escape Tunnel", primitives: ["Burrowing Speed +5"], text: "Move through loose earth at the purchased burrowing speed to make a narrow passage. Stone, foundations, and unsupported ceilings stop or complicate it." },
  { name: "Stone Signal", primitives: ["Ground Contact Echo (10 ft)", "Resonant Alarm"], effects: ["Resonant Warning"], text: "Send a short rehearsed vibration signal through connected stone to a listener able to sense it. Gaps and noise can block the signal." },
  { name: "Colony Message", primitives: ["Scent Signaling"], text: "Send one simple rehearsed message to nearby creatures that can detect and know the scent code. Weather and barriers matter; it is not telepathy." },
  { name: "Deliberate Disguise", primitives: ["Slow Facial Reshaping"], text: "After several minutes, alter superficial facial features. Clothing, voice, size, and close inspection remain separate problems." },
  { name: "Still Camouflage", primitives: ["Still-Surface Camouflage"], text: "Match one background while motionless. Moving, crossing a contrasting surface, or being touched can expose the bearer." },
  { name: "Tinder Spark", primitives: ["Spark-Shedding Skin"], text: "Produce a spark against hard material to ignite suitable tinder. Wet fuel or no air prevents ignition." },
  { name: "Rooted Rest", primitives: ["Soil Disturbance Sense"], text: "While in contact with suitable soil, rest and monitor nearby movement. The table adjudicates nourishment and interruption; it is not automatic Vitality recovery." },
  { name: "Mineral Recollection", primitives: ["Crystal Trace"], text: "On sustained contact with the bearer's living crystal, ask about one recent vibration trace. The GM describes a rough pattern or direction; no full reconstruction, words, or mind reading." },
  { name: "Circuit Trace", primitives: ["Electrical Contact Sense"], text: "Follow a live accessible conductor by touch and identify approximate direction of current. Insulation and dangerous voltage still apply." },
  { name: "Coded Eye Beam", primitives: ["Controlled Eye Light", "Visible Signal Code"], effects: ["Lantern Signal Found"], text: "Display a small light signal to a visible recipient who knows the code. It reveals the sender's position and ends when light is blocked." },
  { name: "Wing-Catch Descent", primitives: ["Controlled Glide"], text: "Spread a gliding surface during a fall and steer within the primitive's stated descent ratio. This never grants hovering or a flying speed." },
  { name: "Delicate Retrieval", primitives: ["Sensitive Branch Feelers"], text: "Feel inside a reachable small cavity and draw out a light unattended object. A trapped, guarded, or heavier object needs its own check or tool." },
  { name: "High-Ledge Recovery", primitives: ["Extended Hand Reach"], text: "Take hold of a nearby ledge or light object across a small gap. This does not extend a weapon or capability range." },
  { name: "Narrow Passage", primitives: ["Soft-Body Compression"], text: "Compress through a plausible opening with suitable time and without blocking equipment. It does not bypass sealed doors or restraints." },
  { name: "Surveyed Traverse", primitives: ["Durable Route Marking", "Fieldcraft Check +2"], effects: ["Surveyed Passage"], text: "Mark and survey one route before travel. On that route, use the linked Fieldcraft benefit when its authored condition holds; the table decides changed terrain." },
  { name: "Hand-Signal Lattice", primitives: ["Visible Signal Code"], effects: ["Lantern Signal Found"], text: "Establish a rehearsed visual code between visible party members. It cannot pass through opaque cover or convey detailed unplanned speech." },
  { name: "Resin Trail", primitives: ["Durable Route Marking"], effects: ["Marked Trail"], text: "Leave a readable trail with carried resin or similar material. Rain, removal, and observers who know the code affect its use." },
  { name: "Witness Seal", primitives: ["Witnessed Mark"], effects: ["Witnessed Oath"], text: "Record voluntarily agreed words on a visible mark. It preserves the terms but confers no obedience or truth detection." },
  { name: "Patch the Seam", primitives: ["Temporary Material Patch"], effects: ["Temporary Patch"], text: "Use compatible carried material to patch one ordinary object for a stated task. State setup time and load limit." },
  { name: "Stone Alarm", primitives: ["Resonant Alarm"], effects: ["Resonant Warning"], text: "Prepare a touched stone or other rigid object to signal once when disturbed. State receiver, duration, and signal path." },
  { name: "Line Catch", primitives: ["Anchored Safety Line"], effects: ["Tethered Safety"], text: "Catch a willing subject or object with a previously anchored carried line within its length and load. It is not an automatic hostile grapple." },
  { name: "Crack Reader", primitives: ["Breach Survey"], effects: ["Observed Breach"], text: "Inspect a reachable wall, plate, or object for a plausible seam. The GM describes what inspection can reveal; exploiting it is a separate action." },
  { name: "Rapid Scaffold", primitives: ["Weather Shelter Frame"], effects: ["Hail Shelter"], text: "Assemble carried supports into temporary shelter at a reachable scene point. State dimensions, setup time, Load, and failure limit; this does not automatically block attacks or conjure a wall." },
  { name: "Breath Share", primitives: ["Small Air Pocket"], effects: ["Held Air"], text: "Provide bounded breathable air to the named subject for the stated task. The table tracks duration and remaining air." },
  { name: "Splint and Rally", primitives: ["Knowledge Check +2", "Minor Die Block"], effects: ["Mended Vitality"], text: "Treat a reachable injured subject with suitable supplies. On success, roll 1d4 healing and enter the Vitality change manually; this does not bypass normal limits." },
  { name: "Doorway Brace", primitives: ["Physical Saving Throw +2"], effects: ["Brace at the Threshold"], text: "Brace at a named doorway against displacement from one approach. Turn this capability on only while the stance holds; turn it off on leaving. Its +2 Physical save applies while active, and the table decides which save the situation calls for." },
  { name: "Hail Canopy", primitives: ["Weather Shelter Frame"], effects: ["Hail Shelter"], text: "Raise a carried frame to shelter a bounded scene area from ordinary weather. It needs setup and does not grant combat cover without a separate rule." },
  { name: "Pressed Escape", primitives: ["Stride Extension +5"], text: "After a stated opening, use ordinary movement to retreat along a legal route. The speed primitive changes the sheet; no extra action or teleportation is granted." },
  { name: "Field Beacon", primitives: ["Visible Signal Code", "Domain of Light"], effects: ["Lantern Signal Found"], source: "MAGICAL", text: "With the purchased Light domain, make a visible signal at a chosen reachable point for allies who know its code. It does not illuminate through cover." },
  { name: "Stone Rampart", primitives: ["Domain of Stone", "Structure Tier I", "Structural Stone Shaping", "Structural Wall"], effects: ["Stone Barrier"], source: "MAGICAL", text: "Using available stone, shape a bounded barrier at a reachable scene point. The Stone domain and structure tier are part of this capability; set dimensions, support, duration, and damage at the table." },
  { name: "Harrowing Phrase", primitives: ["Spoken Doubt"], effects: ["Harrowing Word"], source: "MAGICAL", text: "Deliver an unsettling phrase to a target within the purchased delivery. Record the target's contextual response; this grants no fixed penalty or compulsory behavior." },
  { name: "Deliberate Shot", primitives: ["Practiced Aimed Shot"], text: "Aim and make a ranged attack against a visible target using a range, damage die, and attack already purchased. Aiming adds no automatic roll bonus unless another primitive grants one." },
  { name: "Driving Blow", primitives: ["Driving Strike"], text: "Make a direct attack using the character's purchased attack and output. The weapon or capability determines target and damage; no extra action is granted." },
  { name: "Messenger Cue", primitives: ["Animal Messenger Cue"], text: "Give a trained creature a simple rehearsed delivery task. Resolve travel, hazards, and the creature's actions at the table." },
  { name: "Counterweight Lift", primitives: ["Rigged Counterweight"], text: "Rig carried rope and pulleys to move an ordinary load within the anchor's and gear's ratings. This leaves the character's personal Carry Capacity unchanged." },
  { name: "Stage Mask Disguise", primitives: ["Stage Mask Craft"], text: "Fit a crafted mask and ordinary costume to resemble a chosen role. Voice, height, manner, and close inspection still matter." },
];

// The order matches the numbered tables in the top-down design document.
// Each tuple: direct primitive names; capability names. A blank capability
// list means the heritage is a useful direct-primitive bundle.
const lineageRows: Array<[string, string, string]> = [
  ["Human", "Broad Familiarity", ""],
  ["Mountainfolk", "Adhesive Grip,Climbing Speed +5,Prowess Check +2,Cold Resistance", ""],
  ["Skyborn", "Aero Unlock,Flying Speed +30,Awareness Check +2,Cold Resistance,Physical Saving Throw +2", "Wing-Catch Descent"],
  ["Tidekin", "Aquatic Unlock,Swimming Speed +10,Water Pressure Sense,Cold Resistance", "Current Reading"],
  ["Ironborn", "Retractable Carapace,Temporary Material Patch,Slashing Resistance,Piercing Resistance,Vitality Core Augment II,Carry Capacity Augment +50", "Plate Exchange"],
  ["Forestkind", "Umbral Sight I (Darkvision 60ft),Canopy Footing,Fieldcraft Check +2,Knowledge Check +1", "Canopy Traverse"],
  ["Ashlung", "Ordinary Smoke Filtration,Fire Resistance", ""],
  ["Burrowhide", "Burrowing Speed +5,Ground Contact Echo (10 ft),Prowess Check +2,Carry Capacity Augment +50", "Shallow Escape Tunnel"],
  ["Toneweft", "Ground Contact Echo (10 ft)", "Stone Signal"],
  ["Sporeveil", "Scent Signaling,Poison Resistance,Fieldcraft Check +2", "Colony Message"],
  ["Claymold", "Slow Facial Reshaping,Finesse Check +2,Influence Check +2", "Deliberate Disguise"],
  ["Mirrorhide", "Still-Surface Camouflage,Awareness Check +2,Finesse Check +2", "Still Camouflage"],
  ["Flintskin", "Spark-Shedding Skin,Fire Resistance,Slashing Resistance", "Tinder Spark"],
  ["Rootwaker", "Soil Disturbance Sense,Root Feeding,Fieldcraft Check +2,Vitality Core Augment II,Cold Resistance", "Rooted Rest"],
  ["Latticevein", "Crystal Trace,Awareness Check +2,Thunder Resistance", "Mineral Recollection"],
  ["Coppervein", "Electrical Contact Sense,Lightning Resistance,Knowledge Check +2", "Circuit Trace"],
  ["Nightpupil", "Dim-Light Acuity,Awareness Check +2", ""],
  ["Lantern-eyed", "Controlled Eye Light", "Coded Eye Beam"],
  ["Hollowbone", "Controlled Glide,Climbing Speed +5,Finesse Check +2", "Wing-Catch Descent"],
  ["Antlerhand", "Sensitive Branch Feelers,Finesse Check +2", "Delicate Retrieval"],
  ["Chitterkin", "Ground Contact Echo (10 ft),Physical Saving Throw +1,Piercing Resistance,Awareness Check +2", "Stone Signal"],
  ["Longreach", "Extended Hand Reach,Prowess Check +2,Carry Capacity Augment +50", "High-Ledge Recovery"],
  ["Mirebody", "Soft-Body Compression,Bludgeoning Resistance,Finesse Check +2", "Narrow Passage"],
  ["Kilnmaw", "Kiln-Cured Teeth,Fire Resistance,Prowess Check +2", ""],
];

const upbringingRows: Array<[string, string, string]> = [
  ["Wanderer", "Fieldcraft Proficiency,Stride Extension +5", "Surveyed Traverse"],
  ["Ferry Ward", "Fieldcraft Check +1,Ferry Passage Reading", "Hand-Signal Lattice"],
  ["Marsh Salvager", "Fieldcraft Check +2,Unstable Ground Salvage", "Surveyed Traverse"],
  ["Reef Courier", "Swimming Speed +5,Awareness Check +1,Waterproof Message Wrap", "Resin Trail"],
  ["Caravan Watermaster", "Fieldcraft Check +2,Local Weather Reading,Water Source Survey", "Surveyed Traverse"],
  ["Cartographer's Apprentice", "Awareness Check +1,Durable Route Marking,Useful Field Map", ""],
  ["Wreck Diver", "Swimming Speed +10,Small Salvage Recovery", "Line Catch"],
  ["Road Warden", "Fieldcraft Check +2", "Stone Alarm"],
  ["Tinkerer", "Finesse Proficiency,Temporary Material Patch", "Patch the Seam"],
  ["Bell Foundry Worker", "Finesse Check +1,Bell Tuning", "Stone Alarm"],
  ["Glasswright", "Finesse Check +2,Fine Glasswork", ""],
  ["Quarry Rigger", "Prowess Check +2", "Counterweight Lift,Rapid Scaffold"],
  ["Orchard Tender", "Fieldcraft Check +1,Plant Grafting", ""],
  ["Ward Tailor", "Finesse Check +2", "Hail Canopy"],
  ["Disaster Cook", "Fieldcraft Check +1,Weather Shelter Frame,Improvised Rations", ""],
  ["Rooftop Rigger", "Climbing Speed +10,Finesse Check +2", "Rapid Scaffold"],
  ["Courtier", "Influence Proficiency,Intuition Check +1", "Witness Seal"],
  ["Market Ledger Clerk", "Reason Check +2,Exact Testimony Record,Ledger Trace", ""],
  ["Canal Inspector", "Knowledge Check +2", "Crack Reader"],
  ["Witness Scribe", "Knowledge Check +1,Exact Testimony Record", "Witness Seal"],
  ["City Alarm Keeper", "Awareness Check +1", "Stone Alarm"],
  ["Village Mediator", "Influence Check +2", "Witness Seal"],
  ["Tavern Keeper", "Intuition Check +2,Hospitality Network", ""],
  ["Smuggler's Lookout", "Awareness Check +2,Ordinary Lock Familiarity,Visible Signal Code,Finesse Check +2", "Resin Trail"],
  ["Scholar", "Knowledge Proficiency,Reason Check +1,Focused Research", ""],
  ["Field Surgeon Apprentice", "Knowledge Check +2,Finesse Check +2,Careful Body Preparation,Carry Capacity Augment +50", "Splint and Rally"],
  ["Archive Conservator", "Knowledge Check +2,Temporary Material Patch,Archive Preservation", "Patch the Seam"],
  ["Weather Watcher", "Awareness Check +2,Local Weather Reading", ""],
  ["Reliquary Keeper", "Knowledge Check +2,Touch Memory Impression", "Crack Reader"],
  ["Beast Handler's Aide", "Fieldcraft Check +2,Animal Signal Reading", ""],
  ["Star Surveyor", "Knowledge Check +2,Durable Route Marking,Night Sky Route", "Surveyed Traverse"],
  ["Apothecary Apprentice", "Knowledge Check +2,Fine Glasswork,Plant Grafting,Knowledge Proficiency,Poison Resistance,Reagent Preparation", "Splint and Rally"],
  ["Soldier", "Prowess Proficiency,Physical Saving Throw +2", "Doorway Brace"],
  ["Bridgewatch Veteran", "Physical Saving Throw +2,Bridge Hazard Call", "Doorway Brace"],
  ["Siege Mason", "Fieldcraft Check +3,Domain of Stone,Structure Tier II,Structural Stone Shaping,Carry Capacity Augment +50", "Rapid Scaffold,Stone Rampart,Crack Reader"],
  ["Firewatch Runner", "Stride Extension +5,Ordinary Smoke Filtration", "Hand-Signal Lattice"],
  ["Rescue Diver", "Swimming Speed +10", "Line Catch,Breath Share"],
  ["Prison Keykeeper", "Finesse Check +2,Ordinary Lock Familiarity", ""],
  ["Boundary Keeper", "Fieldcraft Check +2", "Resin Trail,Witness Seal"],
  ["Funeral Tender", "Communion Check +2,Careful Body Preparation", ""],
  ["Theater Maskmaker", "Finesse Check +2", "Stage Mask Disguise"],
  ["Salt-Road Exile", "Fieldcraft Check +2,Local Weather Reading,Salt Route Hazard Sense", ""],
  ["Hollow-City Scavenger", "Awareness Check +2", "Crack Reader"],
  ["Night Census Taker", "Awareness Check +2,Exact Testimony Record,Household Count", ""],
  ["Plague Camp Volunteer", "Knowledge Check +2,Ordinary Smoke Filtration", "Splint and Rally"],
  ["Oath Witness", "Influence Check +2", "Witness Seal"],
  ["Pit Fighter", "Prowess Check +2,Attack Bonus Increment,Ring Opening Read", "Driving Blow"],
  ["Festival Lantern Tender", "Finesse Check +2,Visible Signal Code,Portable Lantern Rig", "Hand-Signal Lattice"],
];

const manifestRows: Array<[string, string, string]> = [
  ["Striker", "Attack Bonus Increment,Heavy Die Block (1d8),Prowess Check +3", "Driving Blow"],
  ["Guardian", "Focused Presence (Global DC Modifier),Physical Saving Throw +2,Vitality Core Augment II,Carry Capacity Augment +50", "Doorway Brace"],
  ["Skirmisher", "Stride Extension +20,Attack Bonus +2", "Pressed Escape"],
  ["Mystic", "Domain of Light,Verb Access Tier II,Near Range,Impact Die Block,Medium Duration", "Field Beacon"],
  ["Artificer", "Finesse Proficiency,Knowledge Check +2,Reason Check +2,Equipment Slot Augment +2,Carry Capacity Augment +50", "Patch the Seam"],
  ["Field Medic", "Knowledge Proficiency,Knowledge Check +3,Finesse Check +2,Carry Capacity Augment +50", "Splint and Rally"],
  ["Elemental Shaper", "Domain of Stone,Verb Access Tier I,Structure Tier I,Structural Stone Shaping,Medium Duration", "Stone Rampart"],
  ["Hexwright", "Domain of Sound,Verb Access Tier I,Influence Check +2,Mental Saving Throw +2,Medium Duration,Near Range,Knowledge Check +2", "Harrowing Phrase"],
  ["Beast Signal Keeper", "Fieldcraft Proficiency,Animal Signal Reading,Awareness Check +3,Near Range,Knowledge Check +2", "Messenger Cue"],
  ["Relic Seeker", "Knowledge Check +2,Touch Memory Impression,Awareness Check +2,Equipment Slot Augment", "Crack Reader,Patch the Seam"],
  ["Treaty Envoy", "Influence Check +PB,Mental Saving Throw +2", "Witness Seal"],
  ["Longshot", "Attack Bonus +2,Near Range,Awareness Check +2,Finesse Check +2", "Deliberate Shot"],
  ["Echo Duelist", "Awareness Check +2,Attack Bonus +2,Finesse Check +2,Physical Saving Throw +2", "Pressed Escape"],
  ["Threshold Warden", "Save DC +2,Vitality Core Augment III,Physical Saving Throw +2,Prowess Check +3", "Doorway Brace,Rapid Scaffold"],
  ["Thread Surgeon", "Finesse Check +3,Knowledge Check +2,Finesse Proficiency,Knowledge Proficiency,Carry Capacity Augment +50", "Patch the Seam,Splint and Rally"],
  ["Terrain Architect", "Domain of Stone,Structure Tier II,Structural Stone Shaping,Long Duration", "Rapid Scaffold,Stone Rampart,Crack Reader"],
  ["Signal Captain", "Influence Check +3,Awareness Check +2,Fieldcraft Check +2,Near Range,Medium Duration,Visible Signal Code", "Hand-Signal Lattice"],
  ["Veil Runner", "Finesse Check +2,Stride Extension +5,Awareness Check +2,Near Range,Climbing Speed +10", "Still Camouflage,Pressed Escape"],
];

const split = (s: string) => s ? s.split(",").map(x => x.trim()).filter(Boolean) : [];
export const heritageRecipes: HeritageRecipe[] = [
  ...lineageRows.map(([name, p, c]) => ({ kind: "LINEAGE" as const, name, primitives: split(p), capabilities: split(c) })),
  ...upbringingRows.map(([name, p, c]) => ({ kind: "UPBRINGING" as const, name, primitives: split(p), capabilities: split(c) })),
  ...manifestRows.map(([name, p, c]) => ({ kind: "MANIFEST" as const, name, primitives: split(p), capabilities: split(c) })),
];
