import {writeFileSync} from "node:fs";
import {pool} from "@/db/client";
import {planItemShelf} from "./item-library-144-plan";
async function main(){const {plan,pending}=await planItemShelf();const out=[
"# Original144-item library ·2 October2026","",
"144 carriers in12 categories of12. Item BU is the deduplicated sum of its ingredient recipe, separate from character primitive BU. Suggested prices remain editable. Two-handed items use at least2 equipment slots. Size governs carried Load separately; carried-only tools and consumables use0 equipment slots. Tiny supplies use the existing1000-per-pouch accounting.","",
"The library includes physical utility permissions, scoped bonuses, prepared effects, and magical carrier recipes. A consumable is expended once. Preparation and ending events are stated in the description. Target damage, healing, displacement, and context-specific consequences are resolved and applied manually. Names such as poisoned or slowed do not introduce universal rules.","",
"Design prompts come from the prior34-game research catalog: portable useful gear from Cairn/Mausritter; material assembly from Zelda/Minecraft; modifying equipment from Warframe/Path of Exile; alternate weapon maneuvers from Monster Hunter; contextual consequences from Fate/Mothership. The names, descriptions, recipes, and numerical choices here are original SwordWeave constructions rather than transcribed text or game rules. See [research provenance](phase4-inspiration-catalog-2026-10.md). Game-icons.net glyphs retain the app's artist attribution andCC BY3.0 credit.","",
`Expansion dependencies not yet saved: ${pending.length}.`,"",
"## Sequence","","Run the item seeder dry-run after expansion publication. Apply only after the lineage-image stage, then run the saved-content audit and multi-budget character checks. No character rows are changed by the seeder.","",
"```sh","npx tsx scripts/seed-item-library-144-2026-10.ts","npx tsx scripts/audit-item-library-144-2026-10.ts --design","npx tsx scripts/seed-item-library-144-2026-10.ts --apply","npx tsx scripts/audit-item-library-144-2026-10.ts","```",""
];for(const category of [...new Set(plan.map(x=>x.category))]){out.push(`## ${category}`,"","| Item | Item BU | Slots / size | Direct primitives | Capabilities / effects |","|---|---:|---|---|---|");for(const x of plan.filter(y=>y.category===category))out.push(`| ${x.name} | ${x.buCost} | ${x.slotCost} / ${x.size.toLowerCase()}${x.isTwoHanded?" / two-handed":""}${x.isNotEquippable?" / carried":""}${x.isConsumable?" / consumable":""} | ${x.primitives.join(", ")||"—"} | ${[...x.capabilities,...x.effects].join(", ")||"—"} |`);out.push("");for(const x of plan.filter(y=>y.category===category))out.push(`**${x.name}.** ${x.description}`,"");}const path="docs/library/item-library-144-2026-10.md";writeFileSync(path,out.join("\n").replace(/Original144/g,"Original 144").replace(/·2 October2026/g,"· 2 October 2026").replace(/in12/g,"in 12").replace(/of12/g,"of 12").replace(/least2/g,"least 2").replace(/use0/g,"use 0").replace(/existing1000/g,"existing 1000").replace(/prior34/g,"prior 34").replace(/andCC BY3.0/g,"and CC BY 3.0"));console.log(path)}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>pool.end());
