/** Public SRD characters. Dry-run default; --apply creates only missing examples. */
import{db,pool,withDatabaseTransaction}from'@/db/client';
import{characters,characterPrimitives,characterCapabilities,characterHeritages,characterItems}from'@/db/schema';
import{demoPlan,demoPrefix}from'./library-demo-characters-plan-2026-10';
async function main(){const plan=await demoPlan();for(const x of plan)console.log(`${x.recipe.name}: ${x.cost}/${x.recipe.budget} character BU; DC ${x.sheet.dc}; Load ${x.sheet.encumbrance.load}/${x.sheet.encumbrance.capacity}; Equip ${x.sheet.encumbrance.equipSlotsUsed}/${x.sheet.encumbrance.equipSlotsAvailable}; ${x.existing?'exists (preserved)':'pending'}`);
 if(!process.argv.includes('--apply')){console.log('DRY RUN: no writes. Items are separate from progression BU.');return;}
 await withDatabaseTransaction(async()=>{for(const x of plan){if(x.existing)continue;const r=x.recipe;
  const lineage=x.heritageRows.find(h=>h.kind==='LINEAGE');const upbringing=x.heritageRows.find(h=>h.kind==='UPBRINGING');const manifest=x.heritageRows.find(h=>h.kind==='MANIFEST');
  const[row]=await db.insert(characters).values({userId:null,name:r.name,sourceOrigin:'SRD',isPublic:true,mode:'PLAY',size:'MEDIUM',level:r.level,attrPhysical:r.attributes[0],attrMental:r.attributes[1],attrMagical:r.attributes[2],attrProficient:r.proficient,startingBu:25,dmBonusBu:x.bonus,buSpent:x.cost,currentVitality:x.sheet.vitality.max,lineageName:lineage?.name,lineageImageUrl:lineage?.imageUrl,lineageDescription:lineage?.description,upbringingName:upbringing?.name,upbringingImageUrl:upbringing?.imageUrl,upbringingDescription:upbringing?.description,manifestName:manifest?.name,practiceSlices:{},backstory:{origin:r.concept,motivation:'Explore this library build and develop it freely.',ties:'Former teachers, fellow travelers and a home worth returning to.',flaw:'Choose a personal complication in play.'},notes:`SRD character build. ${r.budget} BU pool = 25 starting + level progression + ${x.bonus} explicit DM bonus. ${x.cost} spent; ${r.budget-x.cost} unspent. Item BU is separate. Conditions are authored per primitive and off until their stated situation holds. Healing/output changes are resolved manually. ${r.concept}`}).returning();
  if(x.expansion.primitives.length)await db.insert(characterPrimitives).values(x.expansion.primitives.map(p=>({characterId:row.id,primitiveId:p.primitiveId,source:p.source,acquiredAtLevel:1,isMirrored:p.isMirrored,versionId:x.pLatest.get(p.primitiveId)!,slotSource:'PINNED' as const,originHeritageId:p.originHeritageId,originCapabilityId:p.originCapabilityId,originEffectId:p.originEffectId})));
  if(x.expansion.capabilities.length)await db.insert(characterCapabilities).values(x.expansion.capabilities.map(c=>({characterId:row.id,capabilityId:c.capabilityId,acquiredAtLevel:1,versionId:x.cLatest.get(c.capabilityId)!,slotSource:'PINNED' as const,originHeritageId:c.originHeritageId,slotTab:c.originHeritageId?null:'MANIFEST' as const})));
  if(x.expansion.heritages.length)await db.insert(characterHeritages).values(x.expansion.heritages.map(h=>({characterId:row.id,heritageId:h.heritageId,acquiredAtLevel:1,isMirrored:false,versionId:x.hLatest.get(h.heritageId)!,slotSource:'PINNED' as const})));
  if(x.inventory.length)await db.insert(characterItems).values(x.inventory.map(i=>({characterId:row.id,itemId:i.row.id,quantity:1,equipped:i.equipped,versionId:x.iLatest.get(i.row.id)!,slotSource:'PINNED' as const})));
  console.log(`Created SRD character ${r.name}: ${row.id}`);
 }});
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>pool.end());
