/** Disposable real database verification. Every fixture and write is rolled back.
 * pnpm exec tsx scripts/verify-continuity-phase.mts --env <environment file>
 */
import { config } from "dotenv";
import { randomUUID } from "node:crypto";
import assert from "node:assert/strict";
const envFlag=process.argv.indexOf("--env");
config({path:envFlag>=0?process.argv[envFlag+1]:".env.local",quiet:true});
const {db,withDatabaseTransaction,pool}=await import("../src/db/client");
const {sql,eq,and}=await import("drizzle-orm");
const schema=await import("../src/db/schema");
const {createMonster,publishMonster,forkMonster,createMonsterCopy,visibleMonster}=await import("../src/lib/monsters/service");
const {monsterCopyDefinition}=await import("../src/lib/monsters/copy-definition");
const {resolveMonsterComposition}=await import("../src/lib/monsters/composition");
const {resolveMonsterPlay}=await import("../src/lib/monsters/play");
const {mutateMonsterPlay}=await import("../src/lib/monsters/play-service");
const {readPlayState}=await import("../src/lib/play-state/service");
const {PlayConflict}=await import("../src/lib/play-state/model");
const {assertMonsterAudience}=await import("../src/lib/monsters/visibility");
const {recordVersion}=await import("../src/lib/versions/auto-snapshot");
const {publishTarget}=await import("../src/lib/publishing/publish-service");
const actor=`continuity-check-${randomUUID()}`;
const stranger=`continuity-stranger-${randomUUID()}`;
const checks:string[]=[];
const rollback=new Error("VERIFICATION_ROLLBACK");
try{
 await withDatabaseTransaction(async()=>{
  const [profile]=await db.insert(schema.users).values({clerkUserId:actor,username:actor,isPublic:false}).returning();assert(profile);
  const [primitive]=await db.insert(schema.primitives).values({name:"Disposable continuity rule",userId:actor,isPublic:true,category:"STRUCTURAL",buCost:4,isMirrorable:true,mirrorBuCredit:4,hardModifiers:[{kind:"modify",target:"max_vitality",operation:"add",value:5,stacking:"stack"}]}).returning();
  assert(primitive);
  const initialHash=randomUUID();
  const componentVersion=await recordVersion({entityKind:"primitive",entityId:primitive.id,contentHash:initialHash,snapshot:{name:primitive.name,category:primitive.category,buCost:primitive.buCost,hardModifiers:primitive.hardModifiers,isMirrorable:true}});
  const definition={name:"Disposable private sentinel",concept:"Private rollback fixture",budget:25,attributes:{physical:3,mental:0,magical:0},references:[{kind:"PRIMITIVE",id:String(primitive.id),versionId:componentVersion.versionId,quantity:1,isMirrored:false}]};
  const template=await createMonster(actor,definition,false);
  const identical=await publishMonster(template.id,actor,template.definition,false,"PRIVATE");
  assert.equal(identical.version,1);
  const versions=await db.select().from(schema.monsterVersions).where(eq(schema.monsterVersions.monsterId,template.id));
  assert.equal(versions.length,1);checks.push("identical publication keeps one immutable version");
  assert.equal(await visibleMonster(template.id,null),undefined);assert.equal(await visibleMonster(template.id,stranger),undefined);checks.push("private template denies anonymous and other users");
  const fork=await forkMonster(template.id,actor);
  assert.equal(fork.forkedFromId,template.id);assert.equal(fork.definition.references[0]?.versionId,componentVersion.versionId);
  assert(!("resolvedSlots" in fork.definition));checks.push("fork retains exact references without copying published rules");
  const copy=await createMonsterCopy(template.id,actor,"Disposable play copy",1);assert(copy);assert(copy.templateVersionId);assert.equal(copy.definition,null);
  const frozen=await monsterCopyDefinition(copy);
  await publishMonster(template.id,actor,template.definition,true,"PUBLIC");
  const grantedCopy=await createMonsterCopy(template.id,stranger,"Disposable independently granted copy",1);assert(grantedCopy);
  await publishMonster(template.id,actor,template.definition,false,"PRIVATE");
  await publishMonster(template.id,actor,{...template.definition,baselineVitality:30},false,"PRIVATE");
  const pinnedAfterEdit=await monsterCopyDefinition(copy);assert.deepEqual(pinnedAfterEdit,frozen);checks.push("compact private copy keeps its template version after edits");
  let state=await readPlayState("MONSTER_PLAY_COPY",copy.id);
  const injury={opId:randomUUID(),baseRevision:state.revision,changes:[{field:"currentVitality",value:7}]};
  state=await mutateMonsterPlay(actor,copy.id,injury);
  const duplicated=await mutateMonsterPlay(actor,copy.id,injury);assert.equal(duplicated.revision,state.revision);assert.equal(duplicated.overrides["currentVitality"],7);
  await db.update(schema.playStateOperations).set({expiresAt:new Date(Date.now()-1000)}).where(and(eq(schema.playStateOperations.subjectId,copy.id),eq(schema.playStateOperations.opId,injury.opId)));
  await assert.rejects(()=>mutateMonsterPlay(actor,copy.id,injury),PlayConflict);checks.push("duplicate and expired receipt retries cannot apply twice");
  state=await mutateMonsterPlay(actor,copy.id,{opId:randomUUID(),baseRevision:state.revision,changes:[{field:"baselineVitality",value:40}]});
  const slots=await resolveMonsterComposition(frozen,actor);
  const larger=resolveMonsterPlay(frozen,slots,state.overrides,copy.currentVitality).sheet;assert.equal(larger.maximum,45);assert.equal(larger.currentVitality,7);
  state=await mutateMonsterPlay(actor,copy.id,{opId:randomUUID(),baseRevision:state.revision,changes:[{field:"baselineVitality",value:1}]});
  assert.equal(state.overrides["currentVitality"],6);const [persisted]=await db.select().from(schema.monsterCopies).where(eq(schema.monsterCopies.id,copy.id));assert.equal(persisted?.currentVitality,6);checks.push("baseline override applies modifiers, never heals, clamps excess current Vitality");
  await assert.rejects(()=>mutateMonsterPlay(stranger,copy.id,{opId:randomUUID(),baseRevision:state.revision,changes:[{field:"currentVitality",value:1}]}),/not found/);checks.push("other users cannot mutate private play copies");
  await db.execute(sql`SAVEPOINT verify_template_pin`);
  await assert.rejects(()=>db.delete(schema.monsterVersions).where(eq(schema.monsterVersions.id,copy.templateVersionId!)));
  await db.execute(sql`ROLLBACK TO SAVEPOINT verify_template_pin`);checks.push("database FK prevents deleting the copy's pinned version");
  await db.update(schema.primitives).set({isPublic:false}).where(eq(schema.primitives.id,primitive.id));
  await assert.rejects(()=>createMonster(actor,definition,true,undefined,undefined,"PUBLIC"),/Every component/);
  await assert.rejects(()=>createMonster(actor,definition,false,undefined,undefined,"FOLLOWERS_ONLY"),/Every component/);
  await assert.rejects(()=>publishMonster(template.id,actor,template.definition,true,"PUBLIC"),/Every component/);
  await mutateMonsterPlay(actor,copy.id,{opId:randomUUID(),baseRevision:state.revision,changes:[{field:"currentVitality",value:5}]});
  await resolveMonsterComposition(frozen,actor,undefined,{trustedPinnedComposition:true});
  const grantedState=await readPlayState("MONSTER_PLAY_COPY",grantedCopy.id);
  const continued=await mutateMonsterPlay(stranger,grantedCopy.id,{opId:randomUUID(),baseRevision:grantedState.revision,changes:[{field:"currentVitality",value:5}]});assert.equal(continued.overrides["currentVitality"],5);
  await assert.rejects(()=>resolveMonsterComposition(frozen,null),/unavailable/);
  checks.push("private component audience publication is blocked while authorized copy pins survive unsharing");
  const followerPublication=await publishTarget({targetType:"PRIMITIVE",targetId:String(primitive.id),authorId:profile.id,visibility:"FOLLOWERS_ONLY",snapshot:{name:primitive.name,category:primitive.category,buCost:primitive.buCost,hardModifiers:primitive.hardModifiers,isMirrorable:true}});
  await assertMonsterAudience([`primitive:${primitive.id}`],actor,"FOLLOWERS_ONLY");
  await assert.rejects(()=>assertMonsterAudience([`primitive:${primitive.id}`],actor,"PUBLIC"),/Every component/);
  await assert.rejects(()=>assertMonsterAudience([`primitive:${primitive.id}`],stranger,"FOLLOWERS_ONLY"),/Every component/);
  await db.update(schema.publications).set({visibility:"PUBLIC"}).where(eq(schema.publications.id,followerPublication.publicationId));
  await assertMonsterAudience([`primitive:${primitive.id}`],actor,"PUBLIC");
  checks.push("audience checks permit public components and only same-author follower components");
  const versionRows=()=>db.select().from(schema.primitiveVersions).where(eq(schema.primitiveVersions.primitiveId,primitive.id));
  const [original]=await versionRows();assert(original);
  await recordVersion({entityKind:"primitive",entityId:primitive.id,contentHash:randomUUID(),snapshot:{name:"Second disposable version"}});
  await recordVersion({entityKind:"primitive",entityId:primitive.id,contentHash:initialHash,snapshot:{name:"Must never replace first snapshot"}});
  const changed=await publishTarget({targetType:"PRIMITIVE",targetId:String(primitive.id),authorId:profile.id,visibility:"PRIVATE",snapshot:{name:"Third disposable version"}});
  let latestRows=await versionRows();assert.equal(latestRows.filter(row=>row.isLatest).length,1);assert.equal(latestRows.find(row=>row.isLatest)?.id,changed.versionId);
  assert.deepEqual(latestRows.find(row=>row.id===original.id)?.snapshot,original.snapshot);
  const immutable=latestRows.map(({id,snapshot,versionNumber,deltaKind})=>({id,snapshot,versionNumber,deltaKind}));
  await recordVersion({entityKind:"primitive",entityId:primitive.id,contentHash:initialHash,snapshot:{name:"Must still never replace first snapshot"}});
  const unchanged=await publishTarget({targetType:"PRIMITIVE",targetId:String(primitive.id),authorId:profile.id,visibility:"PRIVATE",snapshot:{name:"Third disposable version"}});
  latestRows=await versionRows();assert.equal(unchanged.versionId,changed.versionId);assert.equal(latestRows.filter(row=>row.isLatest).length,1);assert.equal(latestRows.find(row=>row.isLatest)?.id,changed.versionId);
  assert.deepEqual(latestRows.map(({id,snapshot,versionNumber,deltaKind})=>({id,snapshot,versionNumber,deltaKind})).sort((a,b)=>a.id.localeCompare(b.id)),immutable.sort((a,b)=>a.id.localeCompare(b.id)));
  checks.push("publishing after content restore keeps exactly one latest and never rewrites history");
  throw rollback;
 });
 throw new Error("Verification did not roll back.");
}catch(error){if(error!==rollback)throw error;}
finally{await pool.end();}
console.log(JSON.stringify({status:"passed",rolledBack:true,checks},null,2));
