import Link from "next/link";
import { ArrowRight, Clock3, Eye, Flame, Shield, Swords, UsersRound, Zap } from "lucide-react";
import type { Metadata } from "next";
import { PublicNav } from "@/components/home/public-nav";

export const metadata: Metadata = {title:"Combat rhythm · SwordWeave",description:"A shared round of intent, timing, and consequence. Learn the Council Phase, Fast / Measured / Heavy tracks, and reactions in SwordWeave."};
const RHYTHM=[
 {n:"01",icon:UsersRound,title:"Council",body:"The whole party makes one shared plan: declare your intentions, coordinate movement and dependencies, and hear the DM describe the enemies’ round and what your characters can perceive."},
 {n:"02",icon:Eye,title:"Read the scene",body:"The GM considers scale, impact, and complexity. Agree timing, strain, cost, and stakes before committing."},
 {n:"03",icon:Zap,title:"Resolve",body:"Fast, then Measured, then Heavy. Resolve collisions and triggered reactions as the situation changes."},
 {n:"04",icon:Clock3,title:"Carry it forward",body:"Resolve ongoing effects, consequences, and required upkeep. Begin the next Council Phase with the new situation."},
];
const TRACKS=[
 {tone:"teal",name:"Fast",range:"Complexity 0–1",icon:Zap,verb:"Act in the opening.",body:"An immediate response with little preparation. A nearby strike, a move behind cover, a hand reaching for a falling ally.",note:"Resolves first."},
 {tone:"gold",name:"Measured",range:"Complexity 2–3",icon:Swords,verb:"Make the pieces connect.",body:"A deliberate or layered intent. Reposition through danger, divide enemies with a barrier, or bring someone through an escape route.",note:"Resolves after Fast."},
 {tone:"copper",name:"Heavy",range:"Complexity 4+",icon:Flame,verb:"Give the scene a new shape.",body:"An intent requiring substantial construction or concentration. A complex transformation needs time to become real, and the scene may change first.",note:"Resolves last; the intent must still be possible."},
] as const;
export default function CombatPage(){return <div className="sw-home sw-public-site sw-public-site--arcane"><PublicNav/><div id="main-content">
 <header className="sw-public-hero sw-public-hero--compact"><div><p className="sw-public-kicker"><Swords aria-hidden="true"/> The combat rhythm</p><h1 className="sw-public-title">Steel moves.<br />The world answers.<br /><em>Everyone is in the scene.</em></h1><p className="sw-public-deck">Declare your intent together. Let complexity shape when it arrives. React when the moment changes. A fight is a shared situation, unfolding through a shared round.</p><div className="sw-public-actions"><a href="#round" className="sw-cta-primary">Follow a round <ArrowRight aria-hidden="true"/></a><Link href="/character" className="sw-cta-ghost">Build a character first <Shield aria-hidden="true"/></Link></div></div></header>
 <section id="round" className="sw-public-section" aria-labelledby="round-title"><header className="sw-public-section-head"><div><p className="sw-public-kicker">01 / One round, four movements</p><h2 id="round-title">Declare. Commit.<br /><em>See what changes.</em></h2></div><p>The baseline is one Main Intent and one Reaction Slot per round. Movement belongs to the intent. Specific purchased rules can change that baseline.</p></header><ol className="sw-public-rhythm">{RHYTHM.map(phase=><li className="sw-public-panel" key={phase.n}><span className="sw-public-number">{phase.n}</span><phase.icon aria-hidden="true"/><h3>{phase.title}</h3><p>{phase.body}</p></li>)}</ol></section>
 <section className="sw-public-section" aria-labelledby="tracks-title"><header className="sw-public-section-head"><div><p className="sw-public-kicker">02 / When an intent arrives</p><h2 id="tracks-title">Three tracks.<br /><em>One changing battlefield.</em></h2></div><p>Complexity measures what must happen before the action can manifest. The GM assigns the track from the actual intent and its circumstances.</p></header><div className="sw-public-grid">{TRACKS.map(track=><article className="sw-public-panel sw-public-track" data-tone={track.tone} key={track.name}><track.icon aria-hidden="true"/><p className="sw-public-kicker">{track.range}</p><h3>{track.name}</h3><h4>{track.verb}</h4><p>{track.body}</p><strong>{track.note}</strong></article>)}</div></section>
 <section className="sw-public-section" aria-labelledby="scene-title"><header className="sw-public-section-head"><div><p className="sw-public-kicker">03 / Hear it at the table</p><h2 id="scene-title">The bridge is breaking.<br /><em>What do you do?</em></h2></div><p>An example of the conversation. The GM assigns the final track and costs after checking the characters’ access and the scene.</p></header><div className="sw-public-scene">
  <div><span>GM / The situation</span><p>“The guard reaches for the alarm. Below him, the bridge begins to give way.”</p></div>
  <div><span>Player / Main Intent</span><p>“I rush him and pin his arm before he rings it.”</p></div>
  <div><span>Player / A connected plan</span><p>“I make an escape route beside the scout so we can get her off the bridge.”</p></div>
  <div><span>GM / Stakes before commitment</span><p>“The guard’s movement directly conflicts with yours. We’ll resolve who reaches their goal first. The escape route has more pieces to set up; let’s agree its scope, cost and upkeep. If it needs to remain open while everyone crosses, maintaining a smaller path may be easier upfront than creating a huge permanent bridge.”</p></div>
  <div><span>Player / Reaction</span><p>“If the scout falls before the route is ready, I reach out to catch her.”</p></div>
 </div></section>
 <section className="sw-public-section" aria-labelledby="collision-title"><header className="sw-public-section-head"><div><p className="sw-public-kicker">04 / Where intentions meet</p><h2 id="collision-title">Sometimes it is timing.<br /><em>Sometimes it is a struggle.</em></h2></div></header><div className="sw-public-grid">
  <article className="sw-public-panel"><UsersRound aria-hidden="true"/><h3>Working together</h3><p>Allies within the same track choose an order that supports their plan. The GM orders allied opposition as the fiction calls for. A speed contest is unnecessary unless there is a real conflict.</p></article>
  <article className="sw-public-panel"><Zap aria-hidden="true"/><h3>Reaction Clash</h3><p>When opposing intents directly collide within the same track and acting first matters, resolve the timing. Both sides roll d20 + relevant attribute + Proficiency Bonus if trained. A later action is not automatically lost; reassess what remains possible.</p></article>
  <article className="sw-public-panel"><Swords aria-hidden="true"/><h3>Active Contest</h3><p>When the question is whose effort overcomes the other, resolve the struggle using the relevant checks. Pulling against a captor and racing to a door are different problems.</p></article>
 </div></section>
 <section className="sw-public-section" aria-labelledby="reaction-title"><div className="sw-public-duet"><article className="sw-public-panel"><Shield aria-hidden="true"/><p className="sw-public-kicker">05 / The moment between</p><h2 id="reaction-title">Keep a reaction<br /><em>for what matters.</em></h2><p>A reaction answers a clear event: an ally falls, a trap opens, an attack arrives. It is independent of the Main Intent and can happen before or after that intent resolves.</p><p>Pause the triggering action, confirm the response is possible, agree any cost, resolve it, then continue from the changed situation. Reacting does not automatically cancel the trigger.</p></article><article className="sw-public-panel"><Clock3 aria-hidden="true"/><h3>Stay within the moment.</h3><p>The baseline reaction is immediate and limited: self, touch, or a single target, with Complexity 0–1. An ambitious response needs an explicit ruling and appropriate consequences.</p><p>Longer, channelled work stays exposed to the scene. If the circumstances change before it completes, revisit the intent with the GM.</p><div className="sw-public-example"><p>Every ruling should leave the table understanding what happened, what it cost, and what can happen next.</p></div></article></div><div className="sw-public-actions"><Link className="sw-cta-primary" href="/characters/new">Bring your character to the table <ArrowRight aria-hidden="true"/></Link><Link className="sw-cta-ghost" href="/rules#combat">Read the full play guide <ArrowRight aria-hidden="true"/></Link></div></section>
</div></div>;}
