/** Original public examples. Scene advice grants no additional creature mechanics. */
export type SystemEncounterRecipe = {
  key: string;
  name: string;
  environment: string;
  partyBu: number;
  partyItemBu: number;
  partySize: number;
  creatures: { name: string; quantity: number; version: number }[];
  hook: string;
  objective: string;
  terrain: string;
  opening: string;
  tactics: string;
  alternatives: string;
  escalation: string;
  consequence: string;
};
const creature = (name: string, quantity = 1) => ({ name, quantity, version: 1 });
const scene = (recipe: Omit<SystemEncounterRecipe, "partySize">): SystemEncounterRecipe => ({ partySize: 4, ...recipe });
export const systemEncounters: SystemEncounterRecipe[] = [
  scene({
    key: "caravan-at-the-rooted-ford", name: "Caravan at the Rooted Ford", environment: "Wilderness", partyBu: 100, partyItemBu: 0,
    creatures: [creature("Mossback Grazer"), creature("Thornpath Jackal", 2)],
    hook: "A grazer protects its calf at the only dry crossing while hungry jackals circle the caravan.",
    objective: "Get the travelers and their medicine across without separating the calf from its parent. The animals need not be killed.",
    terrain: "A shallow ford, an exposed gravel bank and a root-covered detour. Agree whether wet footing affects movement before an intent depends on it.",
    opening: "The grazer stamps a warning; two jackals watch a loose supply pack. Travelers can retreat to the bank without entering melee.",
    tactics: "The grazer holds its ground with Anchored Stand. The jackals use the actual Driving Blow rules against separated targets and climb along roots; they retreat with food rather than fight to the death.",
    alternatives: "Recover a dropped pack, offer food away from the ford, escort the calf first, or scout the longer route. Animal behavior is a ruling grounded in the scene, not automatic mind control.",
    escalation: "If the party ignores the warning, the grazer blocks the crossing. At Council, describe the jackals approaching the unguarded supplies; let players answer that intent.",
    consequence: "Lost supplies or a delayed medicine delivery are possible costs. Agree the affected item or deadline explicitly; the scene adds no automatic damage or injury rule.",
  }),
  scene({
    key: "the-grove-that-asks-for-help", name: "The Grove That Asks for Help", environment: "Wilderness", partyBu: 200, partyItemBu: 12,
    creatures: [creature("Briar Covenant Tender"), creature("Hollowbark Listener"), creature("Mossback Grazer")],
    hook: "A wounded grove mistakes the party for the woodcutters who damaged its spring.",
    objective: "Reach the blocked spring and show the caretakers what poisoned it. Protecting the grove can end the confrontation.",
    terrain: "A narrow approach between living trunks, a muddy spring basin and a fallen bridge. The obstruction is ordinary timber, not a free magical ward.",
    opening: "The Listener sounds its published alarm. The Tender asks the party to leave while the grazer shields the spring.",
    tactics: "Keep the defender forward and the Tender within its real support range. Tremorsense requires the ground contact described by its primitive; airborne or insulated approaches need ordinary adjudication.",
    alternatives: "Parley from the path, bring evidence of the cutters, or clear the blockage with tools and permission. A successful conversation can recruit help without transferring control of a creature sheet.",
    escalation: "At each Council, state which caretaker is protecting the spring and which is approaching the fallen timber. Move the scene forward when players investigate rather than requiring combat rounds for every task.",
    consequence: "Careless clearing may worsen the blockage or spend supplies. Name the concrete setback and recovery action before applying it; descriptive poison does not create an unlisted poison attack.",
  }),
  scene({
    key: "a-wall-across-the-harvest", name: "A Wall Across the Harvest", environment: "Wilderness", partyBu: 400, partyItemBu: 20,
    creatures: [creature("Floodroot Behemoth"), creature("Cinderbrush Spitter"), creature("Moonspoor Lynx")],
    hook: "A displaced behemoth builds barriers through the fields, and scavengers exploit the confusion.",
    objective: "Open a safe harvest route or divert the behemoth before the wagons arrive. Defeating every animal is only one approach.",
    terrain: "Two farm lanes, a drainage ditch, stacked hay and the barriers the behemoth actually creates with Stone Rampart. Keep any burning hay a separately agreed scene hazard.",
    opening: "A new barrier cuts off the lead wagon. Show the Spitter's firing position and disturbed foliage near the Lynx before resolving any ambush.",
    tactics: "The behemoth divides approaches with its pinned rampart. The Spitter needs a clear lane for its real spray. Still Camouflage is not invisibility; the Lynx should reposition when its hiding place is exposed.",
    alternatives: "Discover the displaced creature's route, move food away from the farms, climb over a suitable barrier, or make a temporary crossing through the ditch.",
    escalation: "If using a wagon-arrival clock, agree its length and which events advance it. It records the scene's urgency, not a new universal encounter timer.",
    consequence: "A damaged wagon, lost crops or a promised repair can matter more than Vitality loss. Let the table choose an intelligible cost for rushed solutions.",
  }),
  scene({
    key: "supplies-under-the-deeprail", name: "Supplies Under the Deeprail", environment: "Subterranean", partyBu: 100, partyItemBu: 8,
    creatures: [creature("Shale Nibbler", 2), creature("Deeprail Rivet Rat")],
    hook: "Scavengers drag the expedition's last repair kit beneath a disused mine railway.",
    objective: "Recover the kit and reach the next shelter. The scavengers care about supplies, not conquest.",
    terrain: "A low service trench, climbable railwork and a wider maintenance bay. Establish which gaps can actually fit each creature before movement begins.",
    opening: "One Nibbler pulls the kit toward a burrow; the other contests food. The Rat is visible beside its scavenged dart tube above the trench.",
    tactics: "Nibblers use their actual burrowing speed to approach and withdraw. The Rat takes deliberate shots from rail cover; the rail itself grants no automatic bonus without a ruling.",
    alternatives: "Trade food, use a pole or line, block a visible burrow entrance, or repair an alternate path. Excavating rock is not a free use of a soil-burrowing speed.",
    escalation: "Tell players when the kit reaches a narrow opening and becomes harder to retrieve. Let an intent intercept the carrier rather than treating the objective as already lost.",
    consequence: "A missing kit can limit repairs until replacement. Record the actual unavailable tools, not a blanket disadvantage on everything underground.",
  }),
  scene({
    key: "the-amber-door-hearing", name: "The Amber Door Hearing", environment: "Subterranean", partyBu: 250, partyItemBu: 12,
    creatures: [creature("Basalt Door Eater"), creature("Amber Vault Hermit"), creature("Lanternblind Mole")],
    hook: "A mineral feeder has sealed a mine refuge, and its caretaker believes opening the door will expose everyone inside.",
    objective: "Gain passage and evacuate the refuge safely. Learn why the caretaker refuses to open it.",
    terrain: "A braced gate, a side seam and a sheltered conversation alcove. The mine's structural risk is visible through cracks and falling grit.",
    opening: "The Mole warns the Hermit of disturbed earth. The Door Eater braces the main gate while the caretaker speaks through a slot.",
    tactics: "Doorway Brace applies only as written. The Hermit uses Patch the Seam within its saved scope; it cannot grant free healing or repair an entire mountain. The Mole scouts disturbed soil rather than detecting every hidden target.",
    alternatives: "Prove a safe evacuation route, shore up the seam, offer minerals away from the gate, or arrange a supervised opening. Inspection can resolve the danger without a fight.",
    escalation: "If the table chooses a collapse clock, advance it only for agreed events such as heavy disturbance or ignored warning signs. Do not secretly add structural damage to each attack.",
    consequence: "A rushed opening may leave a route unusable until repaired. Make the location and repair requirement explicit and allow rescue plans to mitigate it.",
  }),
  scene({
    key: "voices-over-the-sinkhole", name: "Voices Over the Sinkhole", environment: "Subterranean", partyBu: 400, partyItemBu: 20,
    creatures: [creature("Sinkhole Maw"), creature("Cavern Choir Bat", 2)],
    hook: "A cave choir repeats an explorer's last warning above a predator's prepared hunting ground.",
    objective: "Retrieve a trapped explorer and leave the chamber. The repeated warning points toward the unsafe approach.",
    terrain: "A broken central floor, two reachable ledges and a marked route to the explorer. Agree the cost of climbing or securing a rescue line before resolving it.",
    opening: "The bats repeat the warning from opposite ledges. Reveal physical signs of the Maw's anchor trap before characters cross its prepared area.",
    tactics: "Use Gravity Anchor Trap exactly as pinned. The bats apply Harrowing Phrase at its stated range and fly to different ledges; their song does not automatically confuse everyone in the cavern.",
    alternatives: "Approach by a secured line, distract the predator, silence one warning source through negotiation or positioning, or locate a service tunnel.",
    escalation: "At Council, announce whether the Maw is approaching the trapped explorer or guarding its breach. A rescue can interrupt that plan through ordinary intent resolution.",
    consequence: "A severed line or blocked escape may require a new route. Falling and entrapment need explicit table rulings; the terrain description grants no hidden damage package.",
  }),
  scene({
    key: "the-courier-and-the-watch-hound", name: "The Courier and the Watch Hound", environment: "Urban", partyBu: 100, partyItemBu: 8,
    creatures: [creature("Gutterglass Sneak", 2), creature("Bellwatch Hound")],
    hook: "A disguised courier flees with a medicine parcel while a watch hound follows the wrong familiar scent.",
    objective: "Recover the parcel without letting the pursuit trample the market. Discover who actually took it.",
    terrain: "A crowded lane, low awnings and two climbable courtyard walls. Bystanders are scene participants, not added hostile creatures.",
    opening: "The Hound tracks the parcel's former handler; one Sneak changes clothes while the second draws attention at a side alley.",
    tactics: "The Sneaks must establish Deliberate Disguise under its actual rules. The Hound follows scent rather than magically determining guilt; its target can change when the party presents relevant evidence.",
    alternatives: "Call out the parcel's seal, follow rooftops, ask stallholders for directions, or calmly redirect the watch. Any chase checks and movement costs should be agreed in the situation.",
    escalation: "Name the next landmark the courier intends to reach. Offer an interception opportunity each Council rather than measuring the whole chase as one unexplained success roll.",
    consequence: "A spilled stall or injured reputation can create a repair obligation. Specify whose property or trust is affected instead of applying universal social penalties.",
  }),
  scene({
    key: "witness-on-the-roofline", name: "Witness on the Roofline", environment: "Urban", partyBu: 300, partyItemBu: 20,
    creatures: [creature("Tinroof Duelist"), creature("Waxseal Witness"), creature("Rainspout Artillerist")],
    hook: "A protected witness waits above the city while a hired shooter covers the only obvious stair.",
    objective: "Bring the witness and testimony to safety. The Duelist can be challenged, persuaded or bypassed.",
    terrain: "Three connected rooftops, a sheltered stair and a drainage tower with visible firing lanes. Mark distances and reachable edges before declaring leaps.",
    opening: "The Witness asks for escort. The Duelist offers a wager at the stair while the Artillerist signals that the tower is occupied.",
    tactics: "The Artillerist uses Deliberate Shot from a clear lane. The Duelist reserves Deflecting Blow for a real clash. Witness Seal preserves its published evidence; it is not an omniscient truth detector.",
    alternatives: "Negotiate the wager, provide cover through a legal capability, take the hidden service stair after investigation, or secure an extraction line.",
    escalation: "The opposing side intends to move the witness to a different roof, not immediately execute them. Announce that intent and the route it requires.",
    consequence: "Lost testimony, a separated witness or a public debt may follow failure. Keep those outcomes distinct from creature damage and allow recovery scenes.",
  }),
  scene({
    key: "the-clockhouse-under-dispute", name: "The Clockhouse Under Dispute", environment: "Urban", partyBu: 600, partyItemBu: 24,
    creatures: [creature("The Clockhouse Bailiff"), creature("Counterweight Custodian"), creature("Velvet Oath Broker")],
    hook: "A municipal enforcer seals a workshop whose ownership documents contradict one another.",
    objective: "Release the occupants or establish a valid temporary access agreement before the workshop's contents are removed.",
    terrain: "A visible stasis boundary, the front steps, a loading entrance and an open negotiation courtyard. Keep the prepared trap's actual area distinct from the building's outline.",
    opening: "The Bailiff displays its order. The Custodian positions its barricade for worker safety while the Broker offers a narrow bargain.",
    tactics: "Run Temporal Stasis Trap from its pinned rules. Pocket Barricade blocks only what its mechanics permit. The Broker's argument changes no one else's legal rights or choices automatically.",
    alternatives: "Find the conflicting deed, agree an escorted entry, move through an unguarded lawful route, or help evacuate occupants before arguing ownership.",
    escalation: "Use an agreed removal clock if useful. Each advance should correspond to a visible cart departure or rejected access proposal, not an automatic damage tick.",
    consequence: "A lost work order or deferred access is a concrete narrative restriction. Record its issuer and the proof or agreement that can lift it.",
  }),
  scene({
    key: "the-net-at-siltwater-crossing", name: "The Net at Siltwater Crossing", environment: "Aquatic", partyBu: 100, partyItemBu: 8,
    creatures: [creature("Siltfin Biter", 2), creature("Reefglass Needlefish")],
    hook: "A fisher's net is caught across the ferry channel, drawing territorial swimmers to its struggling catch.",
    objective: "Free the net and reopen the crossing without losing the fisher or the ferry pole.",
    terrain: "Shallow banks, deeper water around the net and exposed mooring posts. Agree swimming, breathing and footing requirements for the party before they enter.",
    opening: "Two Biters follow disturbed sediment while the Needlefish circles visible fragments caught in the net.",
    tactics: "Keep the Biters' close attacks and swim speed within their real rules. The Needlefish uses Return-Catch Throw at its stated range; water does not grant an extra projectile attack.",
    alternatives: "Cut the net from shore, lure the shoal with discarded catch, use a secured line, or wait for a safer current. Tools and character abilities must support the proposed method.",
    escalation: "Describe the ferry drifting toward the snag only if the party leaves it unsecured. This can be prevented by a simple sensible action, not always a roll.",
    consequence: "A lost net, delayed crossing or soaked supplies can be the cost. Specify what actually becomes unavailable and how it can be repaired or dried.",
  }),
  scene({
    key: "breath-beneath-the-tidegate", name: "Breath Beneath the Tidegate", environment: "Aquatic", partyBu: 300, partyItemBu: 20,
    creatures: [creature("Tidegate Crab"), creature("Airshare Nautilus"), creature("Drowned Rope Hunter")],
    hook: "A rescue nautilus shelters a stranded worker beneath a jammed sluice while a scavenger lays mooring lines nearby.",
    objective: "Lift the sluice safely and recover the worker. The Nautilus is an ally or protection objective, though included in the saved cast's BU totals.",
    terrain: "A sluice wheel, a maintenance shelf and a visible tangle of abandoned ropes. Show the waterline and relevant distances.",
    opening: "The Crab braces its nesting space. The Nautilus signals the worker's position while the Hunter prepares its actual catch line.",
    tactics: "Use Stone Counterbrace and Line Catch as written. Breath Share is limited by its real target and duration rules; it never means unlimited underwater rescue for the whole party.",
    alternatives: "Operate the wheel from shore, move the Crab's nest carefully, escort the Nautilus or trace the prepared line before approaching the worker.",
    escalation: "A rising-water clock is optional scene advice. Agree its pace and what causes an advance; allow gate operation and secured breathing to change the situation.",
    consequence: "A damaged wheel or abandoned equipment can complicate later passage. Do not invent automatic drowning damage from a narrative countdown without agreeing the hazard rules.",
  }),
  scene({
    key: "the-refuge-and-the-charged-channel", name: "The Refuge and the Charged Channel", environment: "Aquatic", partyBu: 650, partyItemBu: 32,
    creatures: [creature("Pearl Choir Keeper"), creature("Currentglass Ray"), creature("Abyssal Survey Squid")],
    hook: "Refugees cross a flooded sanctuary as a luminous ray patrols the channel and a survey squid follows the vessel's wake.",
    objective: "Escort the refugee boat through a safe route. The Keeper supports the refuge; including it in the cast does not make it an enemy.",
    terrain: "Submerged columns, a sheltered dock and two tidal passages. Ordinary currents and electrical hazards require their own visible, agreed rulings.",
    opening: "The Keeper rallies travelers. The Ray exposes a clear firing lane while the Squid tracks disturbances near the boat.",
    tactics: "Apply the actual Forking Lumen targeting and rally limits. Current Reading supplies only the information its text allows; the Squid's high budget does not grant extra tentacle attacks.",
    alternatives: "Wait for the Keeper's route advice, steer through column cover, distract the Ray or communicate with the observer. Let sensory information change target choices.",
    escalation: "At Council, describe the vessel's intended passage and each creature's response. A pursued boat need not move automatically into a damaging area.",
    consequence: "Separated travelers, a damaged cargo hold or a debt to the sanctuary can follow a risky choice. Record rescue positions and obligations explicitly.",
  }),
  scene({
    key: "dispatch-in-the-updraft", name: "Dispatch in the Updraft", environment: "Aerial", partyBu: 100, partyItemBu: 8,
    creatures: [creature("Gustling Kite"), creature("Copperpin Raptor")],
    hook: "A signal familiar carries the last usable dispatch while a metal-feathered hunter circles the landing mast.",
    objective: "Recover the dispatch and bring the familiar to a safe perch. The Kite can help if the party learns its cue.",
    terrain: "A landing mast, guy ropes and a sheltered platform. Establish climbing distances and safe anchor points; flight alone does not remove range or targeting requirements.",
    opening: "The Kite repeats its messenger cue above the platform. The Raptor announces a diving approach by circling lower.",
    tactics: "The Raptor must approach for its actual Driving Blow. The Kite uses Messenger Cue within its real scope; it cannot deliver a telepathic message to any distant recipient.",
    alternatives: "Call the correct cue, offer a safe landing perch, shield the familiar, or retrieve the message after a controlled release.",
    escalation: "Make a dive intent and its route clear before resolution. The party can answer by changing position or sheltering the objective.",
    consequence: "A torn message or damaged mast can introduce a repair or deciphering problem. A missed cue need not become an unrelated Vitality cost.",
  }),
  scene({
    key: "the-broken-balloon-descent", name: "The Broken Balloon Descent", environment: "Aerial", partyBu: 300, partyItemBu: 24,
    creatures: [creature("Wingstitch Chirurgeon"), creature("Updraft Carapace"), creature("Night Ribbon Glider")],
    hook: "A damaged passenger balloon drifts past a sheltered platform, and a twilight hunter follows its exposed ropes.",
    objective: "Land the passengers safely. The Chirurgeon and Carapace can be allies; saved cast totals include them until the GM changes the preparation.",
    terrain: "A tilting basket, a reachable mooring platform and visible anchor ropes. Agree falling and line-support rulings before committing to a rescue.",
    opening: "The Chirurgeon prepares a recovery approach while the Carapace shields a route. Reveal clues to the Glider's presence before its Greater Invisibility becomes tactically relevant.",
    tactics: "Wing-Catch Descent and Shielded Passage grant only their stated protection. Apply Greater Invisibility's exact duration and costs; the hunter is not automatically undetectable to every sense.",
    alternatives: "Secure the basket, reduce its drift, protect the rescue worker or divert the hunter with suitable bait. Ordinary tools can be useful without purchasing a primitive for every rope knot.",
    escalation: "Advance an optional descent clock for visible loss of altitude or failed anchors, not simply because one real-world minute passes.",
    consequence: "Lost cargo or a stranded passenger can become a follow-up rescue. Keep any injury and its recovery condition explicit and proportionate to the established hazard.",
  }),
  scene({
    key: "corsairs-at-the-storm-shelter", name: "Corsairs at the Storm Shelter", environment: "Aerial", partyBu: 650, partyItemBu: 32,
    creatures: [creature("Thunderhead Bastion"), creature("Skyhook Corsair"), creature("Cloudglass Harrier")],
    hook: "An aerial shelter admits refugees while raiders demand a share of its supplies.",
    objective: "Keep the shelter route open and settle or repel the raid. The Bastion is a potential protector, not inherently a hostile boss.",
    terrain: "A sheltered landing wall, boarding ropes and an exposed supply deck. Distinguish the Bastion's actual Stone Rampart from ordinary storm cover.",
    opening: "The Corsair throws a boarding hook along a visible path. The Harrier claims a firing lane; the Bastion makes space behind its wall.",
    tactics: "Follow Return-Catch Throw and the Harrier's published ability exactly. Neither aerial mobility nor storm imagery grants free attacks, weather control or unlimited protection.",
    alternatives: "Bargain over expendable cargo, cut an accessible boarding line, escort the refugees by another landing or persuade the shelter guardian to permit a controlled exchange.",
    escalation: "At Council, state which rope the Corsair will cross and which supply stack is threatened. Let players protect either people or resources with meaningful intents.",
    consequence: "A surrendered crate, a damaged route or a public promise can conclude the scene. State future obligations in clear language rather than hidden reputation points.",
  }),
  scene({
    key: "the-undelivered-funeral-parcel", name: "The Undelivered Funeral Parcel", environment: "Undead", partyBu: 100, partyItemBu: 0,
    creatures: [creature("Candlebone Porter", 2), creature("Gravechalk Scout")],
    hook: "Two tireless porters block a cemetery lane because their final delivery address no longer exists.",
    objective: "Return the parcel to its rightful memorial or gain passage without disturbing the graves.",
    terrain: "A narrow burial lane, readable grave markers and a ruined delivery arch. The Scout blends with stone but remains subject to its real camouflage limits.",
    opening: "The porters present a faded delivery label. The Scout watches ground contact near the parcel and warns of disturbance.",
    tactics: "The Porters defend their delivery through actual Driving Blow. Tremorsense and Still Camouflage do not grant knowledge of names, intentions or all distant movement.",
    alternatives: "Read the old map, locate the renamed memorial, negotiate temporary custody or escort the porters. Respectful investigation can settle their duty.",
    escalation: "If the parcel is seized, announce the porters' recovery intent. They do not automatically pursue unrelated bystanders across the whole town.",
    consequence: "Disturbed burial markers may require restoration or an apology. Undead identity does not add an unlisted curse, infection or fear aura.",
  }),
  scene({
    key: "names-at-the-ossuary-door", name: "Names at the Ossuary Door", environment: "Undead", partyBu: 300, partyItemBu: 20,
    creatures: [creature("Ossuary Wallbearer"), creature("Ashwake Mourner"), creature("Pale Door Passenger")],
    hook: "A crypt's attendants refuse access until someone restores the erased names above its entrance.",
    objective: "Recover the missing name record or safely retrieve an interred keepsake. The attendants' task is intelligible and negotiable.",
    terrain: "A braced doorway, an exposed inscription wall and a side threshold crossed by the Passenger. Mark which barriers Ghost Walk can actually traverse.",
    opening: "The Wallbearer seals the doorway. The Mourner tends disturbed remains while the Passenger repeats the route of the missing record.",
    tactics: "Doorway Brace and Splint and Rally retain their published limits. The Passenger's traversal is not unlimited intangibility, and undead flavor adds no free resistances beyond pinned primitives.",
    alternatives: "Follow the Passenger's route, consult a local ledger, restore the inscription or negotiate a supervised entry. Offering evidence can change the attendants' intents.",
    escalation: "If the party damages the inscription, name the specific loss and the guardians' response at Council. Avoid turning any accidental touch into an unavoidable full fight.",
    consequence: "An unresolved burial duty can restrict access to this crypt until repaired. Record the affected place and the exact restoration the attendants request.",
  }),
  scene({
    key: "the-procession-that-will-not-pass", name: "The Procession That Will Not Pass", environment: "Undead", partyBu: 650, partyItemBu: 28,
    creatures: [creature("Funeral Bell Chorus"), creature("Rustheart Cavalier")],
    hook: "A funeral procession circles a ruined bridge while a corroded knight challenges anyone carrying a broken oath-token.",
    objective: "Help the procession complete its route or release the travelers caught inside it. Identify whose oath is unfinished.",
    terrain: "A broken bridge, a safe riverside detour and the Chorus's real aura area. Draw the area visibly rather than treating the entire settlement as affected.",
    opening: "The Chorus approaches in a repeated pattern. The Cavalier names the token it seeks before declaring a strike.",
    tactics: "Telegraph Aura of Total Enfeeblement and apply its stated range, saves and costs. Rusting Strike affects only what its saved mechanics permit; it does not destroy every metal item automatically.",
    alternatives: "Restore the token, build a route the procession can use, return stolen ceremonial property or negotiate the knight's task.",
    escalation: "An optional procession clock can mark laps around the trapped travelers. Agree what each lap changes and how opening a safe route halts the cycle.",
    consequence: "An oath obligation or damaged ceremonial gear can become a recoverable cost. No extra death, aging or corruption rule follows merely from the scene's atmosphere.",
  }),
  scene({
    key: "wrong-order-in-the-workshop", name: "Wrong Order in the Workshop", environment: "Constructs", partyBu: 100, partyItemBu: 12,
    creatures: [creature("Rivet Courier", 2), creature("Latchjaw Maintenance Unit")],
    hook: "A repair unit has mistaken the party's equipment for scrap because two couriers delivered conflicting work orders.",
    objective: "Recover the equipment and establish the correct order without wrecking the workshop.",
    terrain: "Sorting benches, a narrow conveyor route and an accessible command desk. Moving machinery is a scene hazard only if the table establishes its effects.",
    opening: "The Maintenance Unit reaches for a tagged tool. Each Courier carries a different dispatch in a waterproof tube.",
    tactics: "Run Scavenged Edge from the unit's actual build. Courier routing is limited by Messenger Route; an order does not become an absolute magical command unless the mechanics say so.",
    alternatives: "Read both orders, correct the scrap tag, distract the unit with legitimate material or reach the command desk. A clear repair instruction may need no roll when nothing opposes it.",
    escalation: "At Council, show which tool will move next on the sorting line. Allow interception instead of declaring equipment irretrievably destroyed.",
    consequence: "A bent tool, missing fitting or delayed repair can be a specific consequence. State the affected item and repair path rather than disabling the whole inventory.",
  }),
  scene({
    key: "hinges-before-the-gate-closes", name: "Hinges Before the Gate Closes", environment: "Constructs", partyBu: 300, partyItemBu: 20,
    creatures: [creature("Gateplate Sentinel"), creature("Silkgear Patchwright"), creature("Prismline Surveyor")],
    hook: "A gate closes on a departing caravan while its repair crew insists that the hinges must be secured first.",
    objective: "Protect the workers, complete the repair or establish an alternate exit before the caravan is trapped.",
    terrain: "An exposed hinge platform, the gate's travel path and a covered control alcove. Show safe working positions and which parts are reachable.",
    opening: "The Sentinel shields vulnerable machinery. The Surveyor marks an intruder while the Patchwright prepares its real repair action.",
    tactics: "Plate Exchange and Patch the Seam use their published target limits. The Surveyor's Coded Eye Beam requires its actual line and range; survey markings add no automatic damage or control.",
    alternatives: "Assist the repair, present authorized work instructions, escort the caravan through a service opening or hold a safe position using a suitable capability.",
    escalation: "If a closure clock is used, advance it only when the machinery actually moves or a repair attempt changes the mechanism. Controls can stop or reverse it when the fiction supports that.",
    consequence: "A delayed departure, exhausted repair supplies or a broken hinge can persist after the scene. Keep their practical effects visible and repairable.",
  }),
  scene({
    key: "the-platform-and-the-visible-contract", name: "The Platform and the Visible Contract", environment: "Constructs", partyBu: 650, partyItemBu: 32,
    creatures: [creature("Counterlift Atlas"), creature("Glasswork Verdict Engine")],
    hook: "A loading platform hangs above a street while an old verdict engine refuses rescue work outside its written contract.",
    objective: "Get the workers off the platform and amend or satisfy the contract. The Atlas can be a strained rescuer rather than an opponent.",
    terrain: "A suspended freight deck, a winding station and a clearly posted contract board. Establish load and reach requirements without inventing a universal weight formula.",
    opening: "The Atlas holds the load through Counterweight Lift. The Engine displays the disputed rescue clause where everyone can read it.",
    tactics: "Use the actual lifting limits and Terms in View text. The Engine's formal language is not automatic mind control, and the Atlas's budget grants no unlisted immunity to overload.",
    alternatives: "Unload the deck, support it with available equipment, provide the named authorization or find a truthful interpretation that permits assistance.",
    escalation: "A strain clock can mark visible mechanical failures if the table agrees it. Each tick should expose a new problem that players can answer, not secretly apply damage to every passenger.",
    consequence: "A broken winch, lost cargo or owed replacement contract can matter after rescue. Choose concrete costs instead of punishing a successful creative plan with arbitrary injury.",
  }),
  scene({
    key: "ink-in-the-wrong-margin", name: "Ink in the Wrong Margin", environment: "Arcane anomalies", partyBu: 100, partyItemBu: 0,
    creatures: [creature("Inkblink Remnant", 2), creature("Parallax Familiar")],
    hook: "Loose spell annotations hide among library shelves while an escaped familiar follows their magical signature.",
    objective: "Recover the annotations before they become scattered or attach to an unrelated research page.",
    terrain: "Readable shelves, open desks and two narrow corners. Ordinary books are fragile scene objects; touching a page does not automatically trigger a spell.",
    opening: "One Remnant echoes from behind a shelf. The Familiar distinguishes trails through Aura Detective within its real scope.",
    tactics: "Use Echo Off the Wall and climbing speed as saved. Aura Detective is not universal knowledge of hidden mechanics or a creature's complete identity.",
    alternatives: "Follow fresh ink marks, secure the disputed pages, ask the Familiar for its trail or provide a blank ledger as a lure.",
    escalation: "At Council, name the page a Remnant intends to reach. Players can protect that page or change the lure rather than waiting for an automatic explosion.",
    consequence: "A scrambled note or lost annotation can require reconstruction. Specify the missing information; the encounter does not grant new spell effects to damaged books.",
  }),
  scene({
    key: "light-across-the-containment-line", name: "Light Across the Containment Line", environment: "Arcane anomalies", partyBu: 300, partyItemBu: 12,
    creatures: [creature("Stillpoint Orb"), creature("Prismspill Doppel"), creature("Parallax Familiar")],
    hook: "A containment laboratory catches a branching-light experiment inside an anchor field while its familiar searches for the missing operator.",
    objective: "Reach the operator or shut down the experiment through an authorized method. The Familiar can identify a trail, not solve the entire laboratory.",
    terrain: "A marked anchor area, glass partitions and a shielded control desk. Establish whether each partition blocks sight and how a valid route reaches the desk.",
    opening: "The Orb maintains its actual trap. The Doppel sends its published lumen effect through a clear lane; the Familiar indicates the operator's last readable trail.",
    tactics: "Gravity Anchor Trap and Forking Lumen retain their exact mechanics. Reflective glass creates no free duplicate attacks, and the containment field covers only its saved area.",
    alternatives: "Approach behind opaque cover, locate the operator's key, follow a safe maintenance passage or persuade the entities to accept a new containment arrangement.",
    escalation: "Use an optional stability clock for visible apparatus failures. State what an advance changes and permit repairs or deactivation to halt it.",
    consequence: "Loss of laboratory access or damaged research material can be an agreed restriction. Define the responsible authority and restoration action instead of an unspecified magical curse.",
  }),
  scene({
    key: "the-repeated-minute", name: "The Repeated Minute", environment: "Arcane anomalies", partyBu: 650, partyItemBu: 24,
    creatures: [creature("Splintertime Custodian"), creature("Mnemonic Surgeon")],
    hook: "A broken ward repeats a guard routine while a caretaker tries to calm the people caught near it.",
    objective: "Recover the trapped researchers and stabilize or bypass the ward. The caretaker can assist rather than oppose the party.",
    terrain: "A visible stasis boundary, a guard route with repeated landmarks and a sheltered treatment room. Repeated description is a clue, not automatic time travel for every creature.",
    opening: "Show the Custodian repeating the same approach. The Surgeon asks for access to one distressed researcher.",
    tactics: "Temporal Stasis Trap must be prepared and resolved under its pinned rules. Kindly, Collect Yourself does not reset all conditions, memories or Vitality beyond its actual text.",
    alternatives: "Time a crossing outside the ward's area, escort the caretaker, identify the faulty anchor or negotiate a safe treatment interval.",
    escalation: "At each Council, repeat the ward's announced intent while changing only what the real scene changed. Do not reset damage, movement or resources merely because the fiction describes a loop.",
    consequence: "A temporarily inaccessible research chamber or a required stabilization task can be the price. Any lasting memory consequence must be agreed and recorded specifically.",
  }),
  scene({
    key: "the-promise-in-the-furnace-road", name: "The Promise in the Furnace Road", environment: "Infernal", partyBu: 100, partyItemBu: 8,
    creatures: [creature("Cinder Contractling"), creature("Furnacejaw Runner")],
    hook: "A courier beast and a tiny record-keeper disagree over who promised to deliver a sealed parcel.",
    objective: "Resolve or fulfill the delivery promise and reopen the road. The recorded terms should be understandable before the party accepts anything.",
    terrain: "A hot but passable work road, a shaded toll shelter and an ordinary parcel station. Heat hazards require explicit scene rules; infernal flavor supplies no automatic damage.",
    opening: "The Contractling offers its witness record. The Runner protects the parcel and declares a visible rush if someone tries to seize it.",
    tactics: "Use Witness Seal for its actual evidentiary role. Driving Blow requires the Runner's real approach; neither creature can bind strangers to a contract without supporting mechanics and consent to the stated fiction.",
    alternatives: "Read the record, deliver the parcel, identify the mistaken recipient or negotiate a substitute carrier. The party can decline a bargain and seek another route.",
    escalation: "State the Runner's intended departure at Council. A missed delivery time is a scene deadline, not a compulsory combat phase effect.",
    consequence: "An accepted delivery obligation or a lost parcel can be recorded as a narrative consequence. Specify recipient, deadline and release condition.",
  }),
  scene({
    key: "workers-behind-the-ash-screen", name: "Workers Behind the Ash Screen", environment: "Infernal", partyBu: 350, partyItemBu: 20,
    creatures: [creature("Ash Veil Collector"), creature("Sulfur Glass Spitter"), creature("Emberfield Tender")],
    hook: "A collector enters a kiln yard during a furnace breach, and a field medic tries to protect workers from the dispute.",
    objective: "Get the workers to shelter and decide how to answer the collector's claim. The Tender is available as an ally or rescue contact.",
    terrain: "A visible soot-screen area, sheltering masonry and a clear work-yard firing lane. Treat smoke, ordinary heat and the spray's mechanics as separate sources.",
    opening: "The Collector prepares Soot Screen Cast while the Spitter claims the open lane. The Tender points to a sheltered route for injured workers.",
    tactics: "Respect the soot ability's actual visibility effects and duration. Glassfall Spray adds no free poison or acid merely because sulfur appears in the creature's name. Cooling Interpose helps only within its published scope.",
    alternatives: "Dispute the claim with evidence, move workers through cover, close a mundane furnace valve or surrender an agreed item instead of fighting.",
    escalation: "An optional evacuation clock can track groups reaching shelter. Advance it for actual escort or worsening access, and let containment work change the pace.",
    consequence: "Lost work time, surrendered collateral or damaged shelter can create understandable stakes. Record the claim's release terms so a narrative debt does not become endless punishment.",
  }),
  scene({
    key: "a-debt-before-the-last-gate", name: "A Debt Before the Last Gate", environment: "Infernal", partyBu: 1000, partyItemBu: 40,
    creatures: [creature("The Last Debt"), creature("Brass Oathkeeper")],
    hook: "An ancient collector demands payment at a guarded gate, but the debt ledger contains a forgotten release clause.",
    objective: "Open the gate by resolving, disputing or escaping the claim. The scene's central conflict is contractual, not necessarily a duel.",
    terrain: "A narrow oath-bound threshold, an open record table and a visible alternate path requiring investigation. Show what the guardian's Anchored Stand actually protects.",
    opening: "The collector states the claimed debt and produces the ledger. The Oathkeeper announces the boundary it must defend.",
    tactics: "The Uncivil Moment applies its exact social mechanics. It does not let the GM dictate a player's real beliefs or consent. The Oathkeeper leaves its post only when its actual build and stated duty support that intent.",
    alternatives: "Find the release clause, identify an earlier payment, negotiate a temporary passage or use a genuinely accessible alternate route.",
    escalation: "At Council, announce whether the collector is closing discussion, claiming collateral or allowing evidence. Do not turn refusal to sign into automatic damage.",
    consequence: "A voluntarily accepted obligation can create a future adventure. State its bounds, recipient and ending condition and distinguish it from any actual mechanical consequence.",
  }),
  scene({
    key: "respect-at-the-seedling-threshold", name: "Respect at the Seedling Threshold", environment: "Ancient guardians", partyBu: 100, partyItemBu: 8,
    creatures: [creature("Threshold Seedling", 2), creature("Stone Script Reader")],
    hook: "Young guardians block a ruin entrance while an attendant searches stone records for the visitors' authority.",
    objective: "Earn passage or discover another permitted approach. Respecting the ruin can solve the scene without defeating its guardians.",
    terrain: "A narrow threshold, readable repair marks and a side approach partly hidden by roots. A clue reveals the route; it does not automatically make it safe.",
    opening: "The Seedlings brace the entrance. The Reader examines an old repair stone and asks why the party wants entry.",
    tactics: "Doorway Brace protects only the space and targets its rules allow. Mineral Recollection reads its actual traces rather than producing every answer about the ruin.",
    alternatives: "Present a legitimate repair purpose, help restore a marker, follow the attendant's evidence or offer to return a stolen fitting.",
    escalation: "If the party forces the threshold, state which guardian contests the entry at Council. A respectful withdrawal should end pursuit unless the scene provides a specific reason otherwise.",
    consequence: "Denied entry or a requested restoration can be a concrete restriction. Record who can lift it and what counts as restitution.",
  }),
  scene({
    key: "patients-on-the-ceremonial-causeway", name: "Patients on the Ceremonial Causeway", environment: "Ancient guardians", partyBu: 400, partyItemBu: 24,
    creatures: [creature("Rootbound Aegis"), creature("Gilded Recovery Hand"), creature("Bronze Path Archer")],
    hook: "Injured explorers shelter behind a guardian while a path sentinel mistakes their escorts for looters.",
    objective: "Move the patients to safety and establish a permitted crossing. The Recovery Hand can support the rescue; it is not required opposition.",
    terrain: "A braced sanctuary entrance, an exposed ceremonial causeway and a sheltered treatment space. Mark the Archer's real sightline and the distance to cover.",
    opening: "The Archer issues a warning. The Aegis protects the doorway while the Recovery Hand requests space to use Gentle Treatment.",
    tactics: "Apply Doorway Brace, Deliberate Shot and Gentle Treatment exactly as pinned. Healing is limited by the saved ability; guardian status does not grant unlimited recovery or protection.",
    alternatives: "Present the patients, negotiate escorted passage, restore a damaged waymark or approach the treatment space through a legal sheltered route.",
    escalation: "At Council, state which patient will move and which crossing the sentinel contests. Give protection and negotiation intents real ways to change those choices.",
    consequence: "A delayed treatment or separated patient can create a follow-up task. Never remove a character's healing entitlement or rest allowance solely because a scene description says the journey was stressful.",
  }),
  scene({
    key: "the-anchor-at-the-first-horizon", name: "The Anchor at the First Horizon", environment: "Ancient guardians", partyBu: 2000, partyItemBu: 80,
    creatures: [creature("The First Horizon Warden"), creature("Equinox Gate Titan")],
    hook: "Ancient protectors hold a reality anchor whose failing alignment threatens the approach to a sealed celestial site.",
    objective: "Stabilize the anchor, establish permission to leave or guide everyone out safely. This is a high-budget scene whose success need not require killing either guardian.",
    terrain: "A visible anchor dais, covered alignment stations and the Titan's clear gaze lanes. Impossible scenery changes no distances or targeting rules unless an authored effect says so.",
    opening: "The Warden identifies the unstable station. The Titan warns against crossing its guarded lane while both offer a chance to explain the party's purpose.",
    tactics: "Spell Counter-Disruption Shield and Medusa's Gaze require their exact pinned triggers, limits and costs. Do not assume automatic petrification, total immunity or unlimited counterspells from the names.",
    alternatives: "Align the stations using legitimate tools or capabilities, satisfy the guardian's stated trial, divert a hazardous line or escort vulnerable companions out.",
    escalation: "An optional stability clock can display visible anchor failures. Agree its maximum and advance triggers; successful repair can pause or reverse progress when the established fiction permits.",
    consequence: "An inaccessible gateway or a bounded stewardship obligation can conclude the scene. A cosmic theme does not justify secret permanent character changes; make any consequence explicit and recoverable.",
  }),
];

export function systemEncounterNote(recipe: SystemEncounterRecipe) {
  return [
    recipe.hook,
    `OBJECTIVE\n${recipe.objective}`,
    `TERRAIN\n${recipe.terrain}`,
    `OPENING\n${recipe.opening}`,
    `TACTICS\n${recipe.tactics}`,
    `OTHER APPROACHES\n${recipe.alternatives}`,
    `ESCALATION\n${recipe.escalation}`,
    `POSSIBLE CONSEQUENCES\n${recipe.consequence}`,
    `BUDGET REFERENCE\nThe saved Party BU (${recipe.partyBu}) and Party Item BU (${recipe.partyItemBu}) are editable illustration values for ${recipe.partySize} characters, not a difficulty rating or recommendation. Replace them with your actual party. All listed creatures contribute to the cast's displayed enemy totals even when a scene casts one as an ally; remove or separate friendly entries when comparing opposition. Creature BU and Item BU remain separate. Similar BU totals do not guarantee similar difficulty.`,
    "RUNNING THIS EXAMPLE\nUse Council → Fast → Measured → Heavy. Declare goals and responses at Council; phase changes apply no damage, expiration or other sheet edits automatically. Narrative advice above grants no additional monster mechanics. Use each pinned capability and primitive as written, and agree any separate scene hazard before applying it.",
  ].join("\n\n");
}
